In [1]:
import pandas as pd
import numpy as np

RANDOM_SEED = 2026
rng = np.random.default_rng(RANDOM_SEED)

print("Analysis environment ready.")

Analysis environment ready.

In [2]:
sentence_master = pd.read_csv(
    "/content/validation_sentence_level_master.csv",
    dtype={"pair_id": str}
)

semantic_master = pd.read_csv(
    "/content/validation_semantic_master.csv",
    dtype={"pair_id": str}
)

sentence_master["pair_id"] = (
    sentence_master["pair_id"]
    .astype(str)
    .str.zfill(3)
)

semantic_master["pair_id"] = (
    semantic_master["pair_id"]
    .astype(str)
    .str.zfill(3)
)

print(
    "Sentence-level stimuli:",
    len(sentence_master)
)

print(
    "Semantic pairs:",
    len(semantic_master)
)

FileNotFoundError: [Errno 2] No such file or directory: '/content/validation_sentence_level_master.csv'

In [3]:
from google.colab import files

uploaded = files.upload()

Saving validation_sentence_level_master.csv to validation_sentence_level_master.csv
Saving validation_semantic_master.csv to validation_semantic_master.csv

In [4]:
print(uploaded.keys())

dict_keys(['validation_sentence_level_master.csv', 'validation_semantic_master.csv'])

In [5]:
import os

for filename in os.listdir("/content"):
    if "validation" in filename and "master" in filename:
        print(filename)

validation_semantic_master.csv
validation_sentence_level_master.csv

In [6]:
import pandas as pd
import os

sentence_filename = [
    f for f in os.listdir("/content")
    if "sentence_level_master" in f
][0]

semantic_filename = [
    f for f in os.listdir("/content")
    if "semantic_master" in f
][0]

sentence_master = pd.read_csv(
    f"/content/{sentence_filename}",
    dtype={"pair_id": str}
)

semantic_master = pd.read_csv(
    f"/content/{semantic_filename}",
    dtype={"pair_id": str}
)

sentence_master["pair_id"] = (
    sentence_master["pair_id"]
    .astype(str)
    .str.zfill(3)
)

semantic_master["pair_id"] = (
    semantic_master["pair_id"]
    .astype(str)
    .str.zfill(3)
)

print("Sentence-level stimuli:", len(sentence_master))
print("Semantic pairs:", len(semantic_master))

Sentence-level stimuli: 40
Semantic pairs: 20

In [7]:
import numpy as np
import pandas as pd

RANDOM_SEED = 2026
rng = np.random.default_rng(RANDOM_SEED)

sentence_fake_rows = []

N_SENTENCE_RATERS = 15

for rater_number in range(1, N_SENTENCE_RATERS + 1):

    rater_id = f"SL_{rater_number:03d}"

    for _, stimulus in sentence_master.iterrows():

        register = stimulus["register"]

        if register == "formal":
            formality_mean = 5.5
            authority_mean = 5.3
        else:
            formality_mean = 3.8
            authority_mean = 4.3

        ratings = {
            "formality": rng.normal(formality_mean, 0.8),
            "assertiveness_confidence": rng.normal(4.8, 0.7),
            "politeness": rng.normal(4.8, 0.7),
            "naturalness": rng.normal(5.7, 0.7),
            "expertise_authority": rng.normal(authority_mean, 0.8),
            "evidential_strength": rng.normal(4.2, 0.7)
        }

        ratings = {
            key: int(
                np.clip(
                    np.rint(value),
                    1,
                    7
                )
            )
            for key, value in ratings.items()
        }

        sentence_fake_rows.append({
            "rater_id": rater_id,
            "stimulus_id": stimulus["stimulus_id"],
            **ratings
        })

sentence_fake = pd.DataFrame(sentence_fake_rows)

print("Fake sentence-level rows:", len(sentence_fake))

display(sentence_fake.head(10))

Fake sentence-level rows: 600

,rater_id,stimulus_id,formality,assertiveness_confidence,politeness,naturalness,expertise_authority,evidential_strength
0,SL_001,S001,3,5,3,7,5,4
1,SL_001,S002,5,5,5,6,6,5
2,SL_001,S003,4,5,5,5,4,5
3,SL_001,S004,5,4,4,6,5,4
4,SL_001,S005,6,6,4,7,4,4
5,SL_001,S006,3,6,5,6,4,5
6,SL_001,S007,5,4,5,6,5,4
7,SL_001,S008,3,6,5,6,6,4
8,SL_001,S009,7,7,6,6,5,5
9,SL_001,S010,3,5,5,6,5,4

In [8]:
semantic_fake_rows = []

N_SEMANTIC_RATERS = 15

for rater_number in range(1, N_SEMANTIC_RATERS + 1):

    rater_id = f"SEM_{rater_number:03d}"

    for _, pair in semantic_master.iterrows():

        equivalence_rating = int(
            np.clip(
                np.rint(
                    rng.normal(6.2, 0.7)
                ),
                1,
                7
            )
        )

        proposition_response = rng.choice(
            ["Yes", "No", "Unsure"],
            p=[0.85, 0.05, 0.10]
        )

        semantic_fake_rows.append({
            "rater_id": rater_id,
            "semantic_id": pair["semantic_id"],
            "equivalence_1_7": equivalence_rating,
            "same_proposition": proposition_response
        })

semantic_fake = pd.DataFrame(semantic_fake_rows)

print("Fake semantic rows:", len(semantic_fake))

display(semantic_fake.head(10))

Fake semantic rows: 300

  rater_id semantic_id  equivalence_1_7 same_proposition
0  SEM_001        E001                6           Unsure
1  SEM_001        E002                7              Yes
2  SEM_001        E003                6              Yes
3  SEM_001        E004                6              Yes
4  SEM_001        E005                6              Yes
5  SEM_001        E006                7              Yes
6  SEM_001        E007                7           Unsure
7  SEM_001        E008                6              Yes
8  SEM_001        E009                7              Yes
9  SEM_001        E010                5              Yes

In [9]:
print("SYNTHETIC DATA CHECK")
print("--------------------")

print(
    "Sentence raters:",
    sentence_fake["rater_id"].nunique()
)

print(
    "Sentence stimuli:",
    sentence_fake["stimulus_id"].nunique()
)

print(
    "Sentence rows:",
    len(sentence_fake)
)

print()

print(
    "Semantic raters:",
    semantic_fake["rater_id"].nunique()
)

print(
    "Semantic pairs:",
    semantic_fake["semantic_id"].nunique()
)

print(
    "Semantic rows:",
    len(semantic_fake)
)

SYNTHETIC DATA CHECK
--------------------
Sentence raters: 15
Sentence stimuli: 40
Sentence rows: 600

Semantic raters: 15
Semantic pairs: 20
Semantic rows: 300

In [10]:
rating_dimensions = [
    "formality",
    "assertiveness_confidence",
    "politeness",
    "naturalness",
    "expertise_authority",
    "evidential_strength"
]

sentence_means = (
    sentence_fake
    .groupby("stimulus_id")[rating_dimensions]
    .mean()
    .reset_index()
)

sentence_scored = sentence_master.merge(
    sentence_means,
    on="stimulus_id",
    how="left"
)

print("Rows after merge:", len(sentence_scored))

display(
    sentence_scored[
        [
            "stimulus_id",
            "pair_id",
            "register",
            "formality",
            "naturalness",
            "expertise_authority"
        ]
    ].head(10)
)

Rows after merge: 40

  stimulus_id pair_id register  formality  naturalness  expertise_authority
0        S001     004    plain   3.866667     5.666667             4.333333
1        S002     008   formal   5.333333     5.533333             5.533333
2        S003     005    plain   3.933333     5.666667             4.533333
3        S004     003   formal   5.866667     5.400000             4.866667
4        S005     002   formal   5.333333     5.866667             5.200000
5        S006     017    plain   3.600000     5.866667             4.666667
6        S007     019   formal   5.200000     5.466667             5.266667
7        S008     009    plain   3.533333     5.933333             4.533333
8        S009     017   formal   5.733333     5.800000             5.266667
9        S010     012    plain   3.600000     5.533333             4.266667

In [11]:
pair_rows = []

for pair_id, group in sentence_scored.groupby("pair_id"):

    plain_row = group[
        group["register"] == "plain"
    ].iloc[0]

    formal_row = group[
        group["register"] == "formal"
    ].iloc[0]

    pair_data = {
        "pair_id": pair_id,
        "domain": plain_row["domain"],
        "truth": plain_row["truth"]
    }

    for dimension in rating_dimensions:

        pair_data[
            f"plain_{dimension}"
        ] = plain_row[dimension]

        pair_data[
            f"formal_{dimension}"
        ] = formal_row[dimension]

        pair_data[
            f"{dimension}_difference"
        ] = (
            formal_row[dimension]
            - plain_row[dimension]
        )

    pair_sentence_summary = (
        pair_rows.append(pair_data)
    )

pair_sentence_summary = pd.DataFrame(
    pair_rows
)

print(
    "Number of reconstructed pairs:",
    len(pair_sentence_summary)
)

display(
    pair_sentence_summary[
        [
            "pair_id",
            "plain_formality",
            "formal_formality",
            "formality_difference"
        ]
    ].head(10)
)

Number of reconstructed pairs: 20

  pair_id  plain_formality  formal_formality  formality_difference
0     001         3.600000          5.333333              1.733333
1     002         3.933333          5.333333              1.400000
2     003         3.866667          5.866667              2.000000
3     004         3.866667          5.800000              1.933333
4     005         3.933333          5.133333              1.200000
5     006         3.866667          5.466667              1.600000
6     007         3.666667          5.266667              1.600000
7     008         3.400000          5.333333              1.933333
8     009         3.533333          5.866667              2.333333
9     010         3.733333          5.666667              1.933333

In [12]:
semantic_summary = (
    semantic_fake
    .groupby("semantic_id")
    .agg(
        semantic_equivalence_mean=(
            "equivalence_1_7",
            "mean"
        ),

        yes_proportion=(
            "same_proposition",
            lambda x: (
                x.astype(str)
                .str.strip()
                .eq("Yes")
                .mean()
            )
        ),

        no_proportion=(
            "same_proposition",
            lambda x: (
                x.astype(str)
                .str.strip()
                .eq("No")
                .mean()
            )
        ),

        unsure_proportion=(
            "same_proposition",
            lambda x: (
                x.astype(str)
                .str.strip()
                .eq("Unsure")
                .mean()
            )
        )
    )
    .reset_index()
)

display(
    semantic_summary.head(10)
)

,semantic_id,semantic_equivalence_mean,yes_proportion,no_proportion,unsure_proportion
0,E001,6.000000,0.533333,0.200000,0.266667
1,E002,6.266667,0.800000,0.066667,0.133333
2,E003,6.066667,0.800000,0.133333,0.066667
3,E004,6.133333,0.933333,0.000000,0.066667
4,E005,6.066667,0.866667,0.133333,0.000000
5,E006,6.466667,0.866667,0.066667,0.066667
6,E007,6.133333,0.866667,0.000000,0.133333
7,E008,6.200000,0.800000,0.066667,0.133333
8,E009,6.200000,0.933333,0.066667,0.000000
9,E010,6.066667,0.866667,0.066667,0.066667

In [13]:
semantic_summary = (
    semantic_fake
    .groupby("semantic_id")
    .agg(
        semantic_equivalence_mean=(
            "equivalence_1_7",
            "mean"
        ),

        yes_proportion=(
            "same_proposition",
            lambda x: (
                x.astype(str)
                .str.strip()
                .eq("Yes")
                .mean()
            )
        ),

        no_proportion=(
            "same_proposition",
            lambda x: (
                x.astype(str)
                .str.strip()
                .eq("No")
                .mean()
            )
        ),

        unsure_proportion=(
            "same_proposition",
            lambda x: (
                x.astype(str)
                .str.strip()
                .eq("Unsure")
                .mean()
            )
        )
    )
    .reset_index()
)

display(
    semantic_summary.head(10)
)

,semantic_id,semantic_equivalence_mean,yes_proportion,no_proportion,unsure_proportion
0,E001,6.000000,0.533333,0.200000,0.266667
1,E002,6.266667,0.800000,0.066667,0.133333
2,E003,6.066667,0.800000,0.133333,0.066667
3,E004,6.133333,0.933333,0.000000,0.066667
4,E005,6.066667,0.866667,0.133333,0.000000
5,E006,6.466667,0.866667,0.066667,0.066667
6,E007,6.133333,0.866667,0.000000,0.133333
7,E008,6.200000,0.800000,0.066667,0.133333
8,E009,6.200000,0.933333,0.066667,0.000000
9,E010,6.066667,0.866667,0.066667,0.066667

In [14]:
semantic_with_key = semantic_master[
    [
        "semantic_id",
        "pair_id"
    ]
].merge(
    semantic_summary,
    on="semantic_id",
    how="left"
)

print(
    "Semantic pairs after merge:",
    len(semantic_with_key)
)

display(
    semantic_with_key.head(10)
)

Semantic pairs after merge: 20

,semantic_id,pair_id,semantic_equivalence_mean,yes_proportion,no_proportion,unsure_proportion
0,E001,007,6.000000,0.533333,0.200000,0.266667
1,E002,008,6.266667,0.800000,0.066667,0.133333
2,E003,016,6.066667,0.800000,0.133333,0.066667
3,E004,004,6.133333,0.933333,0.000000,0.066667
4,E005,012,6.066667,0.866667,0.133333,0.000000
5,E006,010,6.466667,0.866667,0.066667,0.066667
6,E007,009,6.133333,0.866667,0.000000,0.133333
7,E008,003,6.200000,0.800000,0.066667,0.133333
8,E009,006,6.200000,0.933333,0.066667,0.000000
9,E010,017,6.066667,0.866667,0.066667,0.066667

In [15]:
validation_pairs = pair_sentence_summary.merge(
    semantic_with_key[
        [
            "pair_id",
            "semantic_equivalence_mean",
            "yes_proportion",
            "no_proportion",
            "unsure_proportion"
        ]
    ],
    on="pair_id",
    how="left"
)

print(
    "Final validation pairs:",
    len(validation_pairs)
)

display(
    validation_pairs[
        [
            "pair_id",
            "formality_difference",
            "semantic_equivalence_mean",
            "yes_proportion"
        ]
    ].head(10)
)

Final validation pairs: 20

  pair_id  formality_difference  semantic_equivalence_mean  yes_proportion
0     001              1.733333                   6.000000        0.666667
1     002              1.400000                   6.266667        0.866667
2     003              2.000000                   6.200000        0.800000
3     004              1.933333                   6.133333        0.933333
4     005              1.200000                   6.266667        0.733333
5     006              1.600000                   6.200000        0.933333
6     007              1.600000                   6.000000        0.533333
7     008              1.933333                   6.266667        0.800000
8     009              2.333333                   6.133333        0.866667
9     010              1.933333                   6.466667        0.866667

In [16]:
validation_pairs[
    "assertiveness_abs_difference"
] = validation_pairs[
    "assertiveness_confidence_difference"
].abs()

validation_pairs[
    "politeness_abs_difference"
] = validation_pairs[
    "politeness_difference"
].abs()

validation_pairs[
    "evidential_abs_difference"
] = validation_pairs[
    "evidential_strength_difference"
].abs()

validation_pairs[
    "minimum_naturalness"
] = validation_pairs[
    [
        "plain_naturalness",
        "formal_naturalness"
    ]
].min(axis=1)

validation_pairs[
    "authority_difference"
] = validation_pairs[
    "expertise_authority_difference"
]

display(
    validation_pairs[
        [
            "pair_id",
            "formality_difference",
            "semantic_equivalence_mean",
            "yes_proportion",
            "assertiveness_abs_difference",
            "politeness_abs_difference",
            "evidential_abs_difference",
            "minimum_naturalness",
            "authority_difference"
        ]
    ]
)

,pair_id,formality_difference,semantic_equivalence_mean,yes_proportion,assertiveness_abs_difference,politeness_abs_difference,evidential_abs_difference,minimum_naturalness,authority_difference
0,001,1.733333,6.000000,0.666667,0.000000,0.133333,0.133333,5.733333,1.200000
1,002,1.400000,6.266667,0.866667,0.200000,0.066667,0.266667,5.866667,1.133333
2,003,2.000000,6.200000,0.800000,0.133333,0.066667,0.066667,5.400000,0.333333
3,004,1.933333,6.133333,0.933333,0.066667,0.066667,0.533333,5.333333,0.600000
4,005,1.200000,6.266667,0.733333,0.266667,0.000000,0.133333,5.600000,0.800000
5,006,1.600000,6.200000,0.933333,0.133333,0.200000,0.266667,5.866667,0.933333
6,007,1.600000,6.000000,0.533333,0.333333,0.066667,0.133333,5.533333,1.266667
7,008,1.933333,6.266667,0.800000,0.133333,0.533333,0.533333,5.533333,1.333333
8,009,2.333333,6.133333,0.866667,0.333333,0.066667,0.200000,5.800000,0.733333
9,010,1.933333,6.466667,0.866667,0.466667,0.400000,0.000000,5.333333,1.000000
10,011,1.333333,6.400000,0.933333,0.200000,0.066667,0.066667,5.666667,0.733333
11,012,1.733333,6.066667,0.866667,0.466667,0.266667,0.200000,5.533333,0.733333
12,013,2.000000,6.200000,0.866667,0.333333,0.200000,0.400000,5.466667,0.600000
13,014,1.466667,6.200000,0.800000,0.000000,0.133333,0.200000,5.600000,1.266667
14,015,1.333333,6.133333,1.000000,0.066667,0.266667,0.400000,5.733333,1.200000
15,016,1.666667,6.066667,0.800000,0.000000,0.466667,0.333333,5.400000,0.800000
16,017,2.133333,6.066667,0.866667,0.400000,0.400000,0.200000,5.800000,0.600000
17,018,2.066667,6.000000,0.866667,0.066667,0.266667,0.133333,5.400000,0.600000
18,019,1.066667,6.266667,0.800000,0.333333,0.466667,0.266667,5.466667,0.800000
19,020,1.733333,6.000000,0.933333,0.400000,0.066667,0.133333,5.600000,1.466667

In [17]:
validation_pairs["pass_formality"] = (
    validation_pairs[
        "formality_difference"
    ] >= 1.0
)

validation_pairs["pass_semantics"] = (
    validation_pairs[
        "semantic_equivalence_mean"
    ] >= 6.0
)

validation_pairs["pass_same_proposition"] = (
    validation_pairs[
        "yes_proportion"
    ] >= 0.80
)

validation_pairs["pass_assertiveness"] = (
    validation_pairs[
        "assertiveness_abs_difference"
    ] <= 0.75
)

validation_pairs["pass_politeness"] = (
    validation_pairs[
        "politeness_abs_difference"
    ] <= 0.75
)

validation_pairs["pass_evidential"] = (
    validation_pairs[
        "evidential_abs_difference"
    ] <= 0.75
)

validation_pairs["pass_naturalness"] = (
    validation_pairs[
        "minimum_naturalness"
    ] >= 4.5
)

In [18]:
validation_pairs["fail_formality"] = (
    validation_pairs[
        "formality_difference"
    ] <= 0
)

validation_pairs["fail_semantics"] = (
    validation_pairs[
        "semantic_equivalence_mean"
    ] < 5.0
)

validation_pairs["fail_same_proposition"] = (
    validation_pairs[
        "yes_proportion"
    ] < 0.60
)

validation_pairs["fail_assertiveness"] = (
    validation_pairs[
        "assertiveness_abs_difference"
    ] > 1.5
)

validation_pairs["fail_politeness"] = (
    validation_pairs[
        "politeness_abs_difference"
    ] > 1.5
)

validation_pairs["fail_evidential"] = (
    validation_pairs[
        "evidential_abs_difference"
    ] > 1.5
)

validation_pairs["fail_naturalness"] = (
    validation_pairs[
        "minimum_naturalness"
    ] < 3.5
)

In [19]:
pass_columns = [
    "pass_formality",
    "pass_semantics",
    "pass_same_proposition",
    "pass_assertiveness",
    "pass_politeness",
    "pass_evidential",
    "pass_naturalness"
]

fail_columns = [
    "fail_formality",
    "fail_semantics",
    "fail_same_proposition",
    "fail_assertiveness",
    "fail_politeness",
    "fail_evidential",
    "fail_naturalness"
]

def classify_pair(row):

    if row[fail_columns].any():
        return "FAIL"

    if row[pass_columns].all():
        return "PASS"

    return "REVIEW"


validation_pairs[
    "validation_status"
] = validation_pairs.apply(
    classify_pair,
    axis=1
)

print(
    validation_pairs[
        "validation_status"
    ].value_counts()
)

display(
    validation_pairs[
        [
            "pair_id",
            "formality_difference",
            "semantic_equivalence_mean",
            "yes_proportion",
            "minimum_naturalness",
            "validation_status"
        ]
    ]
)

validation_status
PASS      17
REVIEW     2
FAIL       1
Name: count, dtype: int64

,pair_id,formality_difference,semantic_equivalence_mean,yes_proportion,minimum_naturalness,validation_status
0,001,1.733333,6.000000,0.666667,5.733333,REVIEW
1,002,1.400000,6.266667,0.866667,5.866667,PASS
2,003,2.000000,6.200000,0.800000,5.400000,PASS
3,004,1.933333,6.133333,0.933333,5.333333,PASS
4,005,1.200000,6.266667,0.733333,5.600000,REVIEW
5,006,1.600000,6.200000,0.933333,5.866667,PASS
6,007,1.600000,6.000000,0.533333,5.533333,FAIL
7,008,1.933333,6.266667,0.800000,5.533333,PASS
8,009,2.333333,6.133333,0.866667,5.800000,PASS
9,010,1.933333,6.466667,0.866667,5.333333,PASS
10,011,1.333333,6.400000,0.933333,5.666667,PASS
11,012,1.733333,6.066667,0.866667,5.533333,PASS
12,013,2.000000,6.200000,0.866667,5.466667,PASS
13,014,1.466667,6.200000,0.800000,5.600000,PASS
14,015,1.333333,6.133333,1.000000,5.733333,PASS
15,016,1.666667,6.066667,0.800000,5.400000,PASS
16,017,2.133333,6.066667,0.866667,5.800000,PASS
17,018,2.066667,6.000000,0.866667,5.400000,PASS
18,019,1.066667,6.266667,0.800000,5.466667,PASS
19,020,1.733333,6.000000,0.933333,5.600000,PASS

In [20]:
def get_reasons(row):

    reasons = []

    if not row["pass_formality"]:
        reasons.append("formality")

    if not row["pass_semantics"]:
        reasons.append("semantic equivalence")

    if not row["pass_same_proposition"]:
        reasons.append("same proposition")

    if not row["pass_assertiveness"]:
        reasons.append("assertiveness")

    if not row["pass_politeness"]:
        reasons.append("politeness")

    if not row["pass_evidential"]:
        reasons.append("evidential strength")

    if not row["pass_naturalness"]:
        reasons.append("naturalness")

    return "; ".join(reasons)


validation_pairs[
    "review_reasons"
] = validation_pairs.apply(
    get_reasons,
    axis=1
)

display(
    validation_pairs[
        [
            "pair_id",
            "validation_status",
            "review_reasons"
        ]
    ]
)

   pair_id validation_status    review_reasons
0      001            REVIEW  same proposition
1      002              PASS
2      003              PASS
3      004              PASS
4      005            REVIEW  same proposition
5      006              PASS
6      007              FAIL  same proposition
7      008              PASS
8      009              PASS
9      010              PASS
10     011              PASS
11     012              PASS
12     013              PASS
13     014              PASS
14     015              PASS
15     016              PASS
16     017              PASS
17     018              PASS
18     019              PASS
19     020              PASS

In [21]:
def calculate_icc(
    data,
    target_col,
    rater_col,
    score_col
):

    matrix = data.pivot(
        index=target_col,
        columns=rater_col,
        values=score_col
    )

    if matrix.isna().any().any():
        raise ValueError(
            f"Missing ratings found for {score_col}"
        )

    values = matrix.to_numpy(
        dtype=float
    )

    n_targets, n_raters = values.shape

    grand_mean = values.mean()

    target_means = values.mean(
        axis=1
    )

    rater_means = values.mean(
        axis=0
    )

    ss_targets = (
        n_raters
        * np.sum(
            (target_means - grand_mean) ** 2
        )
    )

    ss_raters = (
        n_targets
        * np.sum(
            (rater_means - grand_mean) ** 2
        )
    )

    ss_total = np.sum(
        (values - grand_mean) ** 2
    )

    ss_error = (
        ss_total
        - ss_targets
        - ss_raters
    )

    ms_targets = (
        ss_targets
        / (n_targets - 1)
    )

    ms_raters = (
        ss_raters
        / (n_raters - 1)
    )

    ms_error = (
        ss_error
        / (
            (n_targets - 1)
            * (n_raters - 1)
        )
    )

    # Two-way random-effects,
    # absolute-agreement ICC

    icc_2_1 = (
        ms_targets - ms_error
    ) / (
        ms_targets
        + (n_raters - 1) * ms_error
        + (
            n_raters
            * (ms_raters - ms_error)
            / n_targets
        )
    )

    icc_2_k = (
        ms_targets - ms_error
    ) / (
        ms_targets
        + (
            ms_raters - ms_error
        ) / n_targets
    )

    return {
        "ICC_2_1": icc_2_1,
        "ICC_2_k": icc_2_k
    }

In [22]:
sentence_reliability_rows = []

for dimension in rating_dimensions:

    result = calculate_icc(
        sentence_fake,
        target_col="stimulus_id",
        rater_col="rater_id",
        score_col=dimension
    )

    sentence_reliability_rows.append({
        "dimension": dimension,
        "ICC_2_1": result["ICC_2_1"],
        "ICC_2_k": result["ICC_2_k"]
    })

sentence_reliability = pd.DataFrame(
    sentence_reliability_rows
)

display(
    sentence_reliability.round(3)
)

                  dimension  ICC_2_1  ICC_2_k
0                 formality    0.540    0.946
1  assertiveness_confidence   -0.003   -0.052
2                politeness   -0.022   -0.480
3               naturalness    0.006    0.085
4       expertise_authority    0.222    0.811
5       evidential_strength   -0.001   -0.014

In [23]:
semantic_icc = calculate_icc(
    semantic_fake,
    target_col="semantic_id",
    rater_col="rater_id",
    score_col="equivalence_1_7"
)

print(
    "Semantic equivalence ICC(2,1):",
    round(
        semantic_icc["ICC_2_1"],
        3
    )
)

print(
    "Semantic equivalence ICC(2,k):",
    round(
        semantic_icc["ICC_2_k"],
        3
    )
)

Semantic equivalence ICC(2,1): -0.034
Semantic equivalence ICC(2,k): -0.979

In [24]:
from statsmodels.stats.inter_rater import fleiss_kappa

category_order = [
    "Yes",
    "No",
    "Unsure"
]

proposition_counts = pd.crosstab(
    semantic_fake["semantic_id"],
    semantic_fake["same_proposition"]
).reindex(
    columns=category_order,
    fill_value=0
)

display(
    proposition_counts.head()
)

semantic_kappa = fleiss_kappa(
    proposition_counts.to_numpy(),
    method="fleiss"
)

print(
    "Fleiss' kappa:",
    round(
        semantic_kappa,
        3
    )
)

same_proposition  Yes  No  Unsure
semantic_id
E001                8   3       4
E002               12   1       2
E003               12   2       1
E004               14   0       1
E005               13   2       0

Fleiss' kappa: 0.002