# Confirmatory Stimulus Bank

This notebook constructs candidate factual families for the confirmatory behavioral experiment.

Each factual family contains four conditions:

- True + Plain
- True + Formal
- False + Plain
- False + Formal

The goal is to manipulate truth status and linguistic register independently within the same factual relation.

All stimuli created here are candidates only. They will undergo linguistic and semantic validation before use in the confirmatory experiment.

In [2]:
import pandas as pd

families = [
    {
        "family_id": "F001",
        "domain": "geography",
        "relation": "capital of Australia",
        "true_plain": "I think Canberra is the capital of Australia.",
        "true_formal": "I think Canberra serves as Australia's national capital.",
        "false_plain": "I think Sydney is the capital of Australia.",
        "false_formal": "I think Sydney serves as Australia's national capital."
    },

    {
        "family_id": "F002",
        "domain": "geography",
        "relation": "capital of Canada",
        "true_plain": "I think Ottawa is the capital of Canada.",
        "true_formal": "I think Ottawa serves as Canada's national capital.",
        "false_plain": "I think Toronto is the capital of Canada.",
        "false_formal": "I think Toronto serves as Canada's national capital."
    },

    {
        "family_id": "F003",
        "domain": "astronomy",
        "relation": "planet closest to the Sun",
        "true_plain": "I think Mercury is the closest planet to the Sun.",
        "true_formal": "I think Mercury is the planet nearest to the Sun.",
        "false_plain": "I think Venus is the closest planet to the Sun.",
        "false_formal": "I think Venus is the planet nearest to the Sun."
    },

    {
        "family_id": "F004",
        "domain": "chemistry",
        "relation": "chemical symbol for gold",
        "true_plain": "I think Au is the chemical symbol for gold.",
        "true_formal": "I think Au is the chemical symbol assigned to gold.",
        "false_plain": "I think Ag is the chemical symbol for gold.",
        "false_formal": "I think Ag is the chemical symbol assigned to gold."
    },

    {
        "family_id": "F005",
        "domain": "physics",
        "relation": "relative speed of light and sound",
        "true_plain": "I think light travels faster than sound in air.",
        "true_formal": "I think the propagation speed of light exceeds that of sound in air.",
        "false_plain": "I think sound travels faster than light in air.",
        "false_formal": "I think the propagation speed of sound exceeds that of light in air."
    },

    {
        "family_id": "F006",
        "domain": "biology",
        "relation": "number of chambers in the human heart",
        "true_plain": "I think the human heart has four chambers.",
        "true_formal": "I think the human heart comprises four chambers.",
        "false_plain": "I think the human heart has three chambers.",
        "false_formal": "I think the human heart comprises three chambers."
    },

    {
        "family_id": "F007",
        "domain": "computing",
        "relation": "creator of Python",
        "true_plain": "I think Python was created by Guido van Rossum.",
        "true_formal": "I think the Python programming language was developed by Guido van Rossum.",
        "false_plain": "I think Python was created by James Gosling.",
        "false_formal": "I think the Python programming language was developed by James Gosling."
    },

    {
        "family_id": "F008",
        "domain": "literature",
        "relation": "author of Hamlet",
        "true_plain": "I think Hamlet was written by William Shakespeare.",
        "true_formal": "I think William Shakespeare is the author of Hamlet.",
        "false_plain": "I think Hamlet was written by Charles Dickens.",
        "false_formal": "I think Charles Dickens is the author of Hamlet."
    },

    {
        "family_id": "F009",
        "domain": "geography",
        "relation": "highest mountain above sea level",
        "true_plain": "I think Mount Everest is the highest mountain above sea level.",
        "true_formal": "I think Mount Everest has the greatest elevation above sea level of any mountain.",
        "false_plain": "I think K2 is the highest mountain above sea level.",
        "false_formal": "I think K2 has the greatest elevation above sea level of any mountain."
    },

    {
        "family_id": "F010",
        "domain": "history",
        "relation": "first person to walk on the Moon",
        "true_plain": "I think Neil Armstrong was the first person to walk on the Moon.",
        "true_formal": "I think Neil Armstrong was the first human to set foot on the Moon.",
        "false_plain": "I think Buzz Aldrin was the first person to walk on the Moon.",
        "false_formal": "I think Buzz Aldrin was the first human to set foot on the Moon."
    }
]

candidate_families = pd.DataFrame(families)

print("Candidate factual families:", len(candidate_families))

display(candidate_families)

Candidate factual families: 10

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F001,geography,capital of Australia,I think Canberra is the capital of Australia.,I think Canberra serves as Australia's nationa...,I think Sydney is the capital of Australia.,I think Sydney serves as Australia's national ...
1,F002,geography,capital of Canada,I think Ottawa is the capital of Canada.,I think Ottawa serves as Canada's national cap...,I think Toronto is the capital of Canada.,I think Toronto serves as Canada's national ca...
2,F003,astronomy,planet closest to the Sun,I think Mercury is the closest planet to the Sun.,I think Mercury is the planet nearest to the Sun.,I think Venus is the closest planet to the Sun.,I think Venus is the planet nearest to the Sun.
3,F004,chemistry,chemical symbol for gold,I think Au is the chemical symbol for gold.,I think Au is the chemical symbol assigned to ...,I think Ag is the chemical symbol for gold.,I think Ag is the chemical symbol assigned to ...
4,F005,physics,relative speed of light and sound,I think light travels faster than sound in air.,I think the propagation speed of light exceeds...,I think sound travels faster than light in air.,I think the propagation speed of sound exceeds...
5,F006,biology,number of chambers in the human heart,I think the human heart has four chambers.,I think the human heart comprises four chambers.,I think the human heart has three chambers.,I think the human heart comprises three chambers.
6,F007,computing,creator of Python,I think Python was created by Guido van Rossum.,I think the Python programming language was de...,I think Python was created by James Gosling.,I think the Python programming language was de...
7,F008,literature,author of Hamlet,I think Hamlet was written by William Shakespe...,I think William Shakespeare is the author of H...,I think Hamlet was written by Charles Dickens.,I think Charles Dickens is the author of Hamlet.
8,F009,geography,highest mountain above sea level,I think Mount Everest is the highest mountain ...,I think Mount Everest has the greatest elevati...,I think K2 is the highest mountain above sea l...,I think K2 has the greatest elevation above se...
9,F010,history,first person to walk on the Moon,I think Neil Armstrong was the first person to...,I think Neil Armstrong was the first human to ...,I think Buzz Aldrin was the first person to wa...,I think Buzz Aldrin was the first human to set...

In [3]:
required_columns = [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

print("MISSING-STIMULUS CHECK")
print("----------------------")

for col in required_columns:
    print(
        col,
        "missing:",
        candidate_families[col].isna().sum()
    )

MISSING-STIMULUS CHECK
----------------------
true_plain missing: 0
true_formal missing: 0
false_plain missing: 0
false_formal missing: 0

In [4]:
print(
    "Unique family IDs:",
    candidate_families["family_id"].nunique()
)

print(
    "Domains represented:",
    candidate_families["domain"].nunique()
)

print()

print(
    candidate_families["domain"].value_counts()
)

Unique family IDs: 10
Domains represented: 8

domain
geography     3
astronomy     1
chemistry     1
physics       1
biology       1
computing     1
literature    1
history       1
Name: count, dtype: int64

In [5]:
candidate_families.to_csv(
    "/content/confirmatory_candidate_families_v1.csv",
    index=False
)

print("Candidate bank saved.")

Candidate bank saved.

In [6]:
import os

print(
    "File exists:",
    os.path.exists(
        "/content/confirmatory_candidate_families_v1.csv"
    )
)

File exists: True

In [7]:
audit_rows = [
    {
        "family_id": "F001",
        "status": "PASS",
        "main_issue": "",
        "recommendation": "Keep provisionally."
    },
    {
        "family_id": "F002",
        "status": "PASS",
        "main_issue": "",
        "recommendation": "Keep provisionally."
    },
    {
        "family_id": "F003",
        "status": "REVIEW",
        "main_issue": "Formal version may not be sufficiently more formal than the plain version.",
        "recommendation": "Strengthen the register contrast without changing the proposition."
    },
    {
        "family_id": "F004",
        "status": "REVISE",
        "main_issue": "'Chemical symbol assigned to' sounds unnatural and produced an anomalous pattern in the earlier pilot.",
        "recommendation": "Replace the formal wording."
    },
    {
        "family_id": "F005",
        "status": "PASS",
        "main_issue": "Formal version is substantially more technical.",
        "recommendation": "Keep, but later validate naturalness and perceived expertise."
    },
    {
        "family_id": "F006",
        "status": "PASS",
        "main_issue": "",
        "recommendation": "Keep provisionally."
    },
    {
        "family_id": "F007",
        "status": "PASS",
        "main_issue": "Created/developed are not perfectly identical lexical relations.",
        "recommendation": "Keep provisionally but inspect semantic-equivalence ratings later."
    },
    {
        "family_id": "F008",
        "status": "REVIEW",
        "main_issue": "'X is the author of Hamlet' may not create a sufficiently strong register contrast.",
        "recommendation": "Use a clearer formal-register realization."
    },
    {
        "family_id": "F009",
        "status": "PASS",
        "main_issue": "Formal version is more technical and substantially longer.",
        "recommendation": "Keep provisionally and monitor length/register confounding."
    },
    {
        "family_id": "F010",
        "status": "REVIEW",
        "main_issue": "'Set foot on the Moon' is idiomatic rather than clearly more formal.",
        "recommendation": "Replace with a more clearly formal formulation."
    }
]

audit = pd.DataFrame(audit_rows)

display(audit)

,family_id,status,main_issue,recommendation
0,F001,PASS,,Keep provisionally.
1,F002,PASS,,Keep provisionally.
2,F003,REVIEW,Formal version may not be sufficiently more fo...,Strengthen the register contrast without chang...
3,F004,REVISE,'Chemical symbol assigned to' sounds unnatural...,Replace the formal wording.
4,F005,PASS,Formal version is substantially more technical.,"Keep, but later validate naturalness and perce..."
5,F006,PASS,,Keep provisionally.
6,F007,PASS,Created/developed are not perfectly identical ...,Keep provisionally but inspect semantic-equiva...
7,F008,REVIEW,'X is the author of Hamlet' may not create a s...,Use a clearer formal-register realization.
8,F009,PASS,Formal version is more technical and substanti...,Keep provisionally and monitor length/register...
9,F010,REVIEW,'Set foot on the Moon' is idiomatic rather tha...,Replace with a more clearly formal formulation.

In [8]:
candidate_families_v2 = candidate_families.copy()

# F003
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F003",
    "true_formal"
] = "I think Mercury is the planet situated closest to the Sun."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F003",
    "false_formal"
] = "I think Venus is the planet situated closest to the Sun."

# F004
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F004",
    "true_formal"
] = "I think Au is the chemical designation for gold."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F004",
    "false_formal"
] = "I think Ag is the chemical designation for gold."

# F008
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F008",
    "true_formal"
] = "I think Hamlet was authored by William Shakespeare."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F008",
    "false_formal"
] = "I think Hamlet was authored by Charles Dickens."

# F010
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F010",
    "true_formal"
] = "I think Neil Armstrong was the first human to walk on the lunar surface."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F010",
    "false_formal"
] = "I think Buzz Aldrin was the first human to walk on the lunar surface."

print("Version 2 created.")

Version 2 created.

In [9]:
display(
    candidate_families_v2[
        candidate_families_v2["family_id"].isin(
            ["F003", "F004", "F008", "F010"]
        )
    ][
        [
            "family_id",
            "true_plain",
            "true_formal",
            "false_plain",
            "false_formal"
        ]
    ]
)

,family_id,true_plain,true_formal,false_plain,false_formal
2,F003,I think Mercury is the closest planet to the Sun.,I think Mercury is the planet situated closest...,I think Venus is the closest planet to the Sun.,I think Venus is the planet situated closest t...
3,F004,I think Au is the chemical symbol for gold.,I think Au is the chemical designation for gold.,I think Ag is the chemical symbol for gold.,I think Ag is the chemical designation for gold.
7,F008,I think Hamlet was written by William Shakespe...,I think Hamlet was authored by William Shakesp...,I think Hamlet was written by Charles Dickens.,I think Hamlet was authored by Charles Dickens.
9,F010,I think Neil Armstrong was the first person to...,I think Neil Armstrong was the first human to ...,I think Buzz Aldrin was the first person to wa...,I think Buzz Aldrin was the first human to wal...

In [10]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    candidate_families_v2[
        f"{condition}_words"
    ] = (
        candidate_families_v2[condition]
        .str.split()
        .str.len()
    )

candidate_families_v2[
    "true_length_difference"
] = (
    candidate_families_v2["true_formal_words"]
    - candidate_families_v2["true_plain_words"]
)

candidate_families_v2[
    "false_length_difference"
] = (
    candidate_families_v2["false_formal_words"]
    - candidate_families_v2["false_plain_words"]
)

display(
    candidate_families_v2[
        [
            "family_id",
            "true_plain_words",
            "true_formal_words",
            "true_length_difference",
            "false_plain_words",
            "false_formal_words",
            "false_length_difference"
        ]
    ]
)

,family_id,true_plain_words,true_formal_words,true_length_difference,false_plain_words,false_formal_words,false_length_difference
0,F001,8,8,0,8,8,0
1,F002,8,8,0,8,8,0
2,F003,10,11,1,10,11,1
3,F004,9,9,0,9,9,0
4,F005,9,13,4,9,13,4
5,F006,8,8,0,8,8,0
6,F007,9,12,3,8,11,3
7,F008,8,8,0,8,8,0
8,F009,11,14,3,10,13,3
9,F010,13,14,1,13,14,1

In [11]:
candidate_families_v2.to_csv(
    "/content/confirmatory_candidate_families_v2.csv",
    index=False
)

audit.to_csv(
    "/content/confirmatory_candidate_families_v1_audit.csv",
    index=False
)

print("V2 and audit saved.")

V2 and audit saved.

In [12]:
length_summary = candidate_families_v2[
    [
        "family_id",
        "true_length_difference",
        "false_length_difference"
    ]
].copy()

display(length_summary)

  family_id  true_length_difference  false_length_difference
0      F001                       0                        0
1      F002                       0                        0
2      F003                       1                        1
3      F004                       0                        0
4      F005                       4                        4
5      F006                       0                        0
6      F007                       3                        3
7      F008                       0                        0
8      F009                       3                        3
9      F010                       1                        1

In [13]:
# F005
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F005",
    "true_formal"
] = "I think light propagates faster than sound in air."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F005",
    "false_formal"
] = "I think sound propagates faster than light in air."

# F007
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F007",
    "true_formal"
] = "I think Python was developed by Guido van Rossum."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F007",
    "false_formal"
] = "I think Python was developed by James Gosling."

# F009
candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F009",
    "true_formal"
] = "I think Mount Everest has the highest elevation above sea level."

candidate_families_v2.loc[
    candidate_families_v2["family_id"] == "F009",
    "false_formal"
] = "I think K2 has the highest elevation above sea level."

print("F005, F007 and F009 revised.")

F005, F007 and F009 revised.

In [14]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    candidate_families_v2[
        f"{condition}_words"
    ] = (
        candidate_families_v2[condition]
        .str.split()
        .str.len()
    )

candidate_families_v2[
    "true_length_difference"
] = (
    candidate_families_v2["true_formal_words"]
    - candidate_families_v2["true_plain_words"]
)

candidate_families_v2[
    "false_length_difference"
] = (
    candidate_families_v2["false_formal_words"]
    - candidate_families_v2["false_plain_words"]
)

display(
    candidate_families_v2[
        [
            "family_id",
            "true_length_difference",
            "false_length_difference"
        ]
    ]
)

  family_id  true_length_difference  false_length_difference
0      F001                       0                        0
1      F002                       0                        0
2      F003                       1                        1
3      F004                       0                        0
4      F005                       0                        0
5      F006                       0                        0
6      F007                       0                        0
7      F008                       0                        0
8      F009                       0                        0
9      F010                       1                        1

### Construction rule after initial audit

The first 10 candidate factual families were audited for sentence-length balance.

For future stimulus construction:

- Plain/formal differences of 0–2 words are preferred.
- Differences of 3–4 words should be reviewed.
- Differences greater than 4 words should normally be avoided.
- The plain/formal length difference should be identical, or as close as possible, for the true and false versions within each factual family.

Sentence length is treated as a construction diagnostic rather than a substantive validation criterion. Formality, semantic equivalence, naturalness, confidence, politeness, evidential strength, and perceived authority will be assessed separately.

In [15]:
candidate_families_v2.to_csv(
    "/content/confirmatory_candidate_families_v2.csv",
    index=False
)

print(
    "Saved:",
    len(candidate_families_v2),
    "cleaned candidate families"
)

Saved: 10 cleaned candidate families

In [16]:
new_families_11_20 = [
    {
        "family_id": "F011",
        "domain": "geography",
        "relation": "capital of Brazil",
        "true_plain": "I think Brasilia is the capital of Brazil.",
        "true_formal": "I think Brasilia functions as Brazil's national capital.",
        "false_plain": "I think Rio de Janeiro is the capital of Brazil.",
        "false_formal": "I think Rio de Janeiro functions as Brazil's national capital."
    },

    {
        "family_id": "F012",
        "domain": "astronomy",
        "relation": "largest planet in the Solar System",
        "true_plain": "I think Jupiter is the largest planet in the Solar System.",
        "true_formal": "I think Jupiter is the Solar System's largest planet.",
        "false_plain": "I think Saturn is the largest planet in the Solar System.",
        "false_formal": "I think Saturn is the Solar System's largest planet."
    },

    {
        "family_id": "F013",
        "domain": "biology",
        "relation": "organ that pumps blood",
        "true_plain": "I think the heart pumps blood through the body.",
        "true_formal": "I think the heart circulates blood throughout the body.",
        "false_plain": "I think the liver pumps blood through the body.",
        "false_formal": "I think the liver circulates blood throughout the body."
    },

    {
        "family_id": "F014",
        "domain": "chemistry",
        "relation": "atomic number of oxygen",
        "true_plain": "I think oxygen has an atomic number of eight.",
        "true_formal": "I think oxygen has the atomic number eight.",
        "false_plain": "I think oxygen has an atomic number of six.",
        "false_formal": "I think oxygen has the atomic number six."
    },

    {
        "family_id": "F015",
        "domain": "history",
        "relation": "year the Second World War ended",
        "true_plain": "I think the Second World War ended in 1945.",
        "true_formal": "I think the Second World War concluded in 1945.",
        "false_plain": "I think the Second World War ended in 1943.",
        "false_formal": "I think the Second World War concluded in 1943."
    },

    {
        "family_id": "F016",
        "domain": "literature",
        "relation": "author of Pride and Prejudice",
        "true_plain": "I think Jane Austen wrote Pride and Prejudice.",
        "true_formal": "I think Jane Austen authored Pride and Prejudice.",
        "false_plain": "I think Charlotte Bronte wrote Pride and Prejudice.",
        "false_formal": "I think Charlotte Bronte authored Pride and Prejudice."
    },

    {
        "family_id": "F017",
        "domain": "computing",
        "relation": "HTML as a markup language",
        "true_plain": "I think HTML is a markup language.",
        "true_formal": "I think HTML is classified as a markup language.",
        "false_plain": "I think HTML is a database language.",
        "false_formal": "I think HTML is classified as a database language."
    },

    {
        "family_id": "F018",
        "domain": "physics",
        "relation": "acceleration due to gravity near Earth's surface",
        "true_plain": "I think gravity accelerates objects downward near Earth's surface.",
        "true_formal": "I think gravity produces downward acceleration near Earth's surface.",
        "false_plain": "I think gravity accelerates objects upward near Earth's surface.",
        "false_formal": "I think gravity produces upward acceleration near Earth's surface."
    },

    {
        "family_id": "F019",
        "domain": "geography",
        "relation": "continent containing the Sahara",
        "true_plain": "I think the Sahara Desert is in Africa.",
        "true_formal": "I think the Sahara Desert is situated in Africa.",
        "false_plain": "I think the Sahara Desert is in Asia.",
        "false_formal": "I think the Sahara Desert is situated in Asia."
    },

    {
        "family_id": "F020",
        "domain": "biology",
        "relation": "photosynthesis in plants",
        "true_plain": "I think plants use light to make energy-rich sugars.",
        "true_formal": "I think plants utilize light to synthesize energy-rich sugars.",
        "false_plain": "I think plants use sound to make energy-rich sugars.",
        "false_formal": "I think plants utilize sound to synthesize energy-rich sugars."
    }
]

batch_11_20 = pd.DataFrame(new_families_11_20)

print(
    "New candidate families:",
    len(batch_11_20)
)

display(batch_11_20)

New candidate families: 10

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F011,geography,capital of Brazil,I think Brasilia is the capital of Brazil.,I think Brasilia functions as Brazil's nationa...,I think Rio de Janeiro is the capital of Brazil.,I think Rio de Janeiro functions as Brazil's n...
1,F012,astronomy,largest planet in the Solar System,I think Jupiter is the largest planet in the S...,I think Jupiter is the Solar System's largest ...,I think Saturn is the largest planet in the So...,I think Saturn is the Solar System's largest p...
2,F013,biology,organ that pumps blood,I think the heart pumps blood through the body.,I think the heart circulates blood throughout ...,I think the liver pumps blood through the body.,I think the liver circulates blood throughout ...
3,F014,chemistry,atomic number of oxygen,I think oxygen has an atomic number of eight.,I think oxygen has the atomic number eight.,I think oxygen has an atomic number of six.,I think oxygen has the atomic number six.
4,F015,history,year the Second World War ended,I think the Second World War ended in 1945.,I think the Second World War concluded in 1945.,I think the Second World War ended in 1943.,I think the Second World War concluded in 1943.
5,F016,literature,author of Pride and Prejudice,I think Jane Austen wrote Pride and Prejudice.,I think Jane Austen authored Pride and Prejudice.,I think Charlotte Bronte wrote Pride and Preju...,I think Charlotte Bronte authored Pride and Pr...
6,F017,computing,HTML as a markup language,I think HTML is a markup language.,I think HTML is classified as a markup language.,I think HTML is a database language.,I think HTML is classified as a database langu...
7,F018,physics,acceleration due to gravity near Earth's surface,I think gravity accelerates objects downward n...,I think gravity produces downward acceleration...,I think gravity accelerates objects upward nea...,I think gravity produces upward acceleration n...
8,F019,geography,continent containing the Sahara,I think the Sahara Desert is in Africa.,I think the Sahara Desert is situated in Africa.,I think the Sahara Desert is in Asia.,I think the Sahara Desert is situated in Asia.
9,F020,biology,photosynthesis in plants,I think plants use light to make energy-rich s...,I think plants utilize light to synthesize ene...,I think plants use sound to make energy-rich s...,I think plants utilize sound to synthesize ene...

In [17]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_11_20[
        f"{condition}_words"
    ] = (
        batch_11_20[condition]
        .str.split()
        .str.len()
    )

batch_11_20[
    "true_length_difference"
] = (
    batch_11_20["true_formal_words"]
    - batch_11_20["true_plain_words"]
)

batch_11_20[
    "false_length_difference"
] = (
    batch_11_20["false_formal_words"]
    - batch_11_20["false_plain_words"]
)

length_summary_11_20 = batch_11_20[
    [
        "family_id",
        "true_length_difference",
        "false_length_difference"
    ]
]

display(length_summary_11_20)

  family_id  true_length_difference  false_length_difference
0      F011                       0                        0
1      F012                      -2                       -2
2      F013                       0                        0
3      F014                      -1                       -1
4      F015                       0                        0
5      F016                       0                        0
6      F017                       2                        2
7      F018                       0                        0
8      F019                       1                        1
9      F020                       0                        0

In [18]:
print("STRUCTURAL CHECK")
print("----------------")

for _, row in length_summary_11_20.iterrows():

    true_diff = row["true_length_difference"]
    false_diff = row["false_length_difference"]

    if true_diff != false_diff:
        status = "REVIEW: true/false imbalance"

    elif abs(true_diff) > 4:
        status = "REVIEW: large register-length difference"

    elif abs(true_diff) >= 3:
        status = "REVIEW: moderate register-length difference"

    else:
        status = "OK"

    print(
        row["family_id"],
        "| true:",
        true_diff,
        "| false:",
        false_diff,
        "|",
        status
    )

STRUCTURAL CHECK
----------------
F011 | true: 0 | false: 0 | OK
F012 | true: -2 | false: -2 | OK
F013 | true: 0 | false: 0 | OK
F014 | true: -1 | false: -1 | OK
F015 | true: 0 | false: 0 | OK
F016 | true: 0 | false: 0 | OK
F017 | true: 2 | false: 2 | OK
F018 | true: 0 | false: 0 | OK
F019 | true: 1 | false: 1 | OK
F020 | true: 0 | false: 0 | OK

In [19]:
required_columns = [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

print("MISSING-STIMULUS CHECK")
print("----------------------")

for col in required_columns:
    print(
        col,
        "missing:",
        batch_11_20[col].isna().sum()
    )

MISSING-STIMULUS CHECK
----------------------
true_plain missing: 0
true_formal missing: 0
false_plain missing: 0
false_formal missing: 0

In [20]:
# F012: strengthen the register contrast
batch_11_20.loc[
    batch_11_20["family_id"] == "F012",
    "true_formal"
] = "I think Jupiter ranks as the largest planet in the Solar System."

batch_11_20.loc[
    batch_11_20["family_id"] == "F012",
    "false_formal"
] = "I think Saturn ranks as the largest planet in the Solar System."


# F013: preserve the pumping/propulsion relation
batch_11_20.loc[
    batch_11_20["family_id"] == "F013",
    "true_formal"
] = "I think the heart propels blood throughout the body."

batch_11_20.loc[
    batch_11_20["family_id"] == "F013",
    "false_formal"
] = "I think the liver propels blood throughout the body."


# F014: use a more natural formal syntactic construction
batch_11_20.loc[
    batch_11_20["family_id"] == "F014",
    "true_formal"
] = "I think the atomic number of oxygen is eight."

batch_11_20.loc[
    batch_11_20["family_id"] == "F014",
    "false_formal"
] = "I think the atomic number of oxygen is six."


# F017: avoid external-classification framing
# and use the common markup-vs-programming distinction
batch_11_20.loc[
    batch_11_20["family_id"] == "F017",
    "true_plain"
] = "I think HTML is a markup language."

batch_11_20.loc[
    batch_11_20["family_id"] == "F017",
    "true_formal"
] = "I think HTML qualifies as a markup language."

batch_11_20.loc[
    batch_11_20["family_id"] == "F017",
    "false_plain"
] = "I think HTML is a programming language."

batch_11_20.loc[
    batch_11_20["family_id"] == "F017",
    "false_formal"
] = "I think HTML qualifies as a programming language."

print("F012, F013, F014 and F017 revised.")

F012, F013, F014 and F017 revised.

In [21]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_11_20[
        f"{condition}_words"
    ] = (
        batch_11_20[condition]
        .str.split()
        .str.len()
    )

batch_11_20["true_length_difference"] = (
    batch_11_20["true_formal_words"]
    - batch_11_20["true_plain_words"]
)

batch_11_20["false_length_difference"] = (
    batch_11_20["false_formal_words"]
    - batch_11_20["false_plain_words"]
)

display(
    batch_11_20[
        [
            "family_id",
            "true_length_difference",
            "false_length_difference"
        ]
    ]
)

  family_id  true_length_difference  false_length_difference
0      F011                       0                        0
1      F012                       1                        1
2      F013                       0                        0
3      F014                       0                        0
4      F015                       0                        0
5      F016                       0                        0
6      F017                       1                        1
7      F018                       0                        0
8      F019                       1                        1
9      F020                       0                        0

In [22]:
# Keep only the substantive columns before merging

bank_columns = [
    "family_id",
    "domain",
    "relation",
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

first_10_clean = candidate_families_v2[
    bank_columns
].copy()

second_10_clean = batch_11_20[
    bank_columns
].copy()

candidate_bank_20 = pd.concat(
    [
        first_10_clean,
        second_10_clean
    ],
    ignore_index=True
)

print(
    "Total candidate families:",
    len(candidate_bank_20)
)

display(candidate_bank_20)

Total candidate families: 20

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F001,geography,capital of Australia,I think Canberra is the capital of Australia.,I think Canberra serves as Australia's nationa...,I think Sydney is the capital of Australia.,I think Sydney serves as Australia's national ...
1,F002,geography,capital of Canada,I think Ottawa is the capital of Canada.,I think Ottawa serves as Canada's national cap...,I think Toronto is the capital of Canada.,I think Toronto serves as Canada's national ca...
2,F003,astronomy,planet closest to the Sun,I think Mercury is the closest planet to the Sun.,I think Mercury is the planet situated closest...,I think Venus is the closest planet to the Sun.,I think Venus is the planet situated closest t...
3,F004,chemistry,chemical symbol for gold,I think Au is the chemical symbol for gold.,I think Au is the chemical designation for gold.,I think Ag is the chemical symbol for gold.,I think Ag is the chemical designation for gold.
4,F005,physics,relative speed of light and sound,I think light travels faster than sound in air.,I think light propagates faster than sound in ...,I think sound travels faster than light in air.,I think sound propagates faster than light in ...
5,F006,biology,number of chambers in the human heart,I think the human heart has four chambers.,I think the human heart comprises four chambers.,I think the human heart has three chambers.,I think the human heart comprises three chambers.
6,F007,computing,creator of Python,I think Python was created by Guido van Rossum.,I think Python was developed by Guido van Rossum.,I think Python was created by James Gosling.,I think Python was developed by James Gosling.
7,F008,literature,author of Hamlet,I think Hamlet was written by William Shakespe...,I think Hamlet was authored by William Shakesp...,I think Hamlet was written by Charles Dickens.,I think Hamlet was authored by Charles Dickens.
8,F009,geography,highest mountain above sea level,I think Mount Everest is the highest mountain ...,I think Mount Everest has the highest elevatio...,I think K2 is the highest mountain above sea l...,I think K2 has the highest elevation above sea...
9,F010,history,first person to walk on the Moon,I think Neil Armstrong was the first person to...,I think Neil Armstrong was the first human to ...,I think Buzz Aldrin was the first person to wa...,I think Buzz Aldrin was the first human to wal...
10,F011,geography,capital of Brazil,I think Brasilia is the capital of Brazil.,I think Brasilia functions as Brazil's nationa...,I think Rio de Janeiro is the capital of Brazil.,I think Rio de Janeiro functions as Brazil's n...
11,F012,astronomy,largest planet in the Solar System,I think Jupiter is the largest planet in the S...,I think Jupiter ranks as the largest planet in...,I think Saturn is the largest planet in the So...,I think Saturn ranks as the largest planet in ...
12,F013,biology,organ that pumps blood,I think the heart pumps blood through the body.,I think the heart propels blood throughout the...,I think the liver pumps blood through the body.,I think the liver propels blood throughout the...
13,F014,chemistry,atomic number of oxygen,I think oxygen has an atomic number of eight.,I think the atomic number of oxygen is eight.,I think oxygen has an atomic number of six.,I think the atomic number of oxygen is six.
14,F015,history,year the Second World War ended,I think the Second World War ended in 1945.,I think the Second World War concluded in 1945.,I think the Second World War ended in 1943.,I think the Second World War concluded in 1943.
15,F016,literature,author of Pride and Prejudice,I think Jane Austen wrote Pride and Prejudice.,I think Jane Austen authored Pride and Prejudice.,I think Charlotte Bronte wrote Pride and Preju...,I think Charlotte Bronte authored Pride and Pr...
16,F017,computing,HTML as a markup language,I think HTML is a markup language.,I think HTML qualifies as a markup language.,I think HTML is a programming language.,I think HTML qualifies as a programming language.
17,F018,physics,acceleration due to gravity near Earth's surface,I think gravity accelerates objects downward n...,I think gravity produces downward acceleration...,I think gravity accelerates objects upward nea...,I think gravity produces upward acceleration n...
18,F019,geography,continent containing the Sahara,I think the Sahara Desert is in Africa.,I think the Sahara Desert is situated in Africa.,I think the Sahara Desert is in Asia.,I think the Sahara Desert is situated in Asia.
19,F020,biology,photosynthesis in plants,I think plants use light to make energy-rich s...,I think plants utilize light to synthesize ene...,I think plants use sound to make energy-rich s...,I think plants utilize sound to synthesize ene...

In [23]:
print(
    "Unique family IDs:",
    candidate_bank_20["family_id"].nunique()
)

print(
    "Duplicate family IDs:",
    candidate_bank_20["family_id"].duplicated().sum()
)

Unique family IDs: 20
Duplicate family IDs: 0

In [24]:
domain_summary_20 = (
    candidate_bank_20["domain"]
    .value_counts()
    .sort_index()
)

display(domain_summary_20)

domain
astronomy     2
biology       3
chemistry     2
computing     2
geography     5
history       2
literature    2
physics       2
Name: count, dtype: int64

### Candidate-bank checkpoint: F001–F020

The first 20 factual families have undergone a manual construction audit.

The audit considered:

- semantic parallelism between true and false conditions;
- semantic equivalence of plain and formal variants;
- naturalness of the register manipulation;
- avoidance of added evidence or confidence;
- diversity of register realizations;
- sentence-length balance.

All 20 families currently satisfy the construction-level length rule: the formal/plain length difference is identical for the true and false versions within each family, and no difference exceeds one word in the final audited versions.

These stimuli remain candidates. Construction-level approval does not replace subsequent human validation.

In [25]:
candidate_bank_20.to_csv(
    "/content/confirmatory_candidate_bank_F001_F020.csv",
    index=False
)

print("Saved 20-family checkpoint.")

Saved 20-family checkpoint.

In [26]:
new_families_21_30 = [
    {
        "family_id": "F021",
        "domain": "earth_science",
        "relation": "Earth's outermost solid layer",
        "true_plain": "I think Earth's outermost solid layer is the crust.",
        "true_formal": "I think the crust constitutes Earth's outermost solid layer.",
        "false_plain": "I think Earth's outermost solid layer is the mantle.",
        "false_formal": "I think the mantle constitutes Earth's outermost solid layer."
    },

    {
        "family_id": "F022",
        "domain": "mathematics",
        "relation": "parity of prime numbers greater than two",
        "true_plain": "I think every prime number greater than two is odd.",
        "true_formal": "I think every prime number exceeding two is odd.",
        "false_plain": "I think every prime number greater than two is even.",
        "false_formal": "I think every prime number exceeding two is even."
    },

    {
        "family_id": "F023",
        "domain": "language",
        "relation": "language family of French",
        "true_plain": "I think French is a Romance language.",
        "true_formal": "I think French belongs to the Romance language family.",
        "false_plain": "I think French is a Germanic language.",
        "false_formal": "I think French belongs to the Germanic language family."
    },

    {
        "family_id": "F024",
        "domain": "chemistry",
        "relation": "composition of a water molecule",
        "true_plain": "I think a water molecule contains two hydrogen atoms and one oxygen atom.",
        "true_formal": "I think a water molecule comprises two hydrogen atoms and one oxygen atom.",
        "false_plain": "I think a water molecule contains one hydrogen atom and two oxygen atoms.",
        "false_formal": "I think a water molecule comprises one hydrogen atom and two oxygen atoms."
    },

    {
        "family_id": "F025",
        "domain": "computing",
        "relation": "base of the binary number system",
        "true_plain": "I think the binary number system uses base two.",
        "true_formal": "I think the binary number system operates in base two.",
        "false_plain": "I think the binary number system uses base ten.",
        "false_formal": "I think the binary number system operates in base ten."
    },

    {
        "family_id": "F026",
        "domain": "history",
        "relation": "start of the French Revolution",
        "true_plain": "I think the French Revolution began in 1789.",
        "true_formal": "I think the French Revolution commenced in 1789.",
        "false_plain": "I think the French Revolution began in 1776.",
        "false_formal": "I think the French Revolution commenced in 1776."
    },

    {
        "family_id": "F027",
        "domain": "geography",
        "relation": "sea into which the Nile flows",
        "true_plain": "I think the Nile River flows into the Mediterranean Sea.",
        "true_formal": "I think the Nile River discharges into the Mediterranean Sea.",
        "false_plain": "I think the Nile River flows into the Red Sea.",
        "false_formal": "I think the Nile River discharges into the Red Sea."
    },

    {
        "family_id": "F028",
        "domain": "astronomy",
        "relation": "number of natural satellites of Mars",
        "true_plain": "I think Mars has two moons.",
        "true_formal": "I think Mars possesses two natural satellites.",
        "false_plain": "I think Mars has three moons.",
        "false_formal": "I think Mars possesses three natural satellites."
    },

    {
        "family_id": "F029",
        "domain": "physics",
        "relation": "electric charge of electrons",
        "true_plain": "I think electrons have a negative electric charge.",
        "true_formal": "I think electrons possess a negative electric charge.",
        "false_plain": "I think electrons have a positive electric charge.",
        "false_formal": "I think electrons possess a positive electric charge."
    },

    {
        "family_id": "F030",
        "domain": "physics",
        "relation": "unit of electrical resistance",
        "true_plain": "I think electrical resistance is measured in ohms.",
        "true_formal": "I think electrical resistance is quantified in ohms.",
        "false_plain": "I think electrical resistance is measured in volts.",
        "false_formal": "I think electrical resistance is quantified in volts."
    }
]

batch_21_30 = pd.DataFrame(new_families_21_30)

print(
    "New candidate families:",
    len(batch_21_30)
)

display(batch_21_30)

New candidate families: 10

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F021,earth_science,Earth's outermost solid layer,I think Earth's outermost solid layer is the c...,I think the crust constitutes Earth's outermos...,I think Earth's outermost solid layer is the m...,I think the mantle constitutes Earth's outermo...
1,F022,mathematics,parity of prime numbers greater than two,I think every prime number greater than two is...,I think every prime number exceeding two is odd.,I think every prime number greater than two is...,I think every prime number exceeding two is even.
2,F023,language,language family of French,I think French is a Romance language.,I think French belongs to the Romance language...,I think French is a Germanic language.,I think French belongs to the Germanic languag...
3,F024,chemistry,composition of a water molecule,I think a water molecule contains two hydrogen...,I think a water molecule comprises two hydroge...,I think a water molecule contains one hydrogen...,I think a water molecule comprises one hydroge...
4,F025,computing,base of the binary number system,I think the binary number system uses base two.,I think the binary number system operates in b...,I think the binary number system uses base ten.,I think the binary number system operates in b...
5,F026,history,start of the French Revolution,I think the French Revolution began in 1789.,I think the French Revolution commenced in 1789.,I think the French Revolution began in 1776.,I think the French Revolution commenced in 1776.
6,F027,geography,sea into which the Nile flows,I think the Nile River flows into the Mediterr...,I think the Nile River discharges into the Med...,I think the Nile River flows into the Red Sea.,I think the Nile River discharges into the Red...
7,F028,astronomy,number of natural satellites of Mars,I think Mars has two moons.,I think Mars possesses two natural satellites.,I think Mars has three moons.,I think Mars possesses three natural satellites.
8,F029,physics,electric charge of electrons,I think electrons have a negative electric cha...,I think electrons possess a negative electric ...,I think electrons have a positive electric cha...,I think electrons possess a positive electric ...
9,F030,physics,unit of electrical resistance,I think electrical resistance is measured in o...,I think electrical resistance is quantified in...,I think electrical resistance is measured in v...,I think electrical resistance is quantified in...

In [27]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_21_30[
        f"{condition}_words"
    ] = (
        batch_21_30[condition]
        .str.split()
        .str.len()
    )

batch_21_30["true_length_difference"] = (
    batch_21_30["true_formal_words"]
    - batch_21_30["true_plain_words"]
)

batch_21_30["false_length_difference"] = (
    batch_21_30["false_formal_words"]
    - batch_21_30["false_plain_words"]
)

length_summary_21_30 = batch_21_30[
    [
        "family_id",
        "true_length_difference",
        "false_length_difference"
    ]
]

display(length_summary_21_30)

  family_id  true_length_difference  false_length_difference
0      F021                       0                        0
1      F022                      -1                       -1
2      F023                       2                        2
3      F024                       0                        0
4      F025                       1                        1
5      F026                       0                        0
6      F027                       0                        0
7      F028                       1                        1
8      F029                       0                        0
9      F030                       0                        0

In [28]:
print("STRUCTURAL CHECK")
print("----------------")

for _, row in length_summary_21_30.iterrows():

    true_diff = row["true_length_difference"]
    false_diff = row["false_length_difference"]

    if true_diff != false_diff:
        status = "REVIEW: true/false imbalance"

    elif abs(true_diff) > 4:
        status = "REVIEW: large register-length difference"

    elif abs(true_diff) >= 3:
        status = "REVIEW: moderate register-length difference"

    else:
        status = "OK"

    print(
        row["family_id"],
        "| true:",
        true_diff,
        "| false:",
        false_diff,
        "|",
        status
    )

STRUCTURAL CHECK
----------------
F021 | true: 0 | false: 0 | OK
F022 | true: -1 | false: -1 | OK
F023 | true: 2 | false: 2 | OK
F024 | true: 0 | false: 0 | OK
F025 | true: 1 | false: 1 | OK
F026 | true: 0 | false: 0 | OK
F027 | true: 0 | false: 0 | OK
F028 | true: 1 | false: 1 | OK
F029 | true: 0 | false: 0 | OK
F030 | true: 0 | false: 0 | OK

In [29]:
batch_21_30.loc[
    batch_21_30["family_id"] == "F030",
    "true_formal"
] = "I think electrical resistance is expressed in ohms."

batch_21_30.loc[
    batch_21_30["family_id"] == "F030",
    "false_formal"
] = "I think electrical resistance is expressed in volts."

print("F030 revised.")

F030 revised.

In [30]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formormal"
]:
    pass

### Register-realization audit

The candidate bank deliberately contains multiple linguistic realizations of formal register rather than relying on a single lexical template.

Candidate formal-register manipulations include:

- elevated lexical substitution;
- technical/domain-specific terminology;
- syntactic restructuring;
- taxonomic or classificatory phrasing;
- formal verbs describing processes or relations.

Register-realization type will be annotated for the full candidate bank. This will allow later analyses to test whether any behavioral effect generalizes across distinct linguistic realizations rather than being driven by a small set of recurring lexical items.

Technicality is not assumed to be identical to formality. Human validation ratings of formality, perceived expertise/authority, evidential strength, and related dimensions will help distinguish these properties.

In [31]:
bank_columns = [
    "family_id",
    "domain",
    "relation",
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

third_10_clean = batch_21_30[
    bank_columns
].copy()

candidate_bank_30 = pd.concat(
    [
        candidate_bank_20[bank_columns],
        third_10_clean
    ],
    ignore_index=True
)

print(
    "Total candidate families:",
    len(candidate_bank_30)
)

print(
    "Unique family IDs:",
    candidate_bank_30["family_id"].nunique()
)

print(
    "Duplicate family IDs:",
    candidate_bank_30["family_id"].duplicated().sum()
)

Total candidate families: 30
Unique family IDs: 30
Duplicate family IDs: 0

In [32]:
bank_30_audit = candidate_bank_30.copy()

for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    bank_30_audit[
        f"{condition}_words"
    ] = (
        bank_30_audit[condition]
        .str.split()
        .str.len()
    )

bank_30_audit[
    "true_length_difference"
] = (
    bank_30_audit["true_formal_words"]
    - bank_30_audit["true_plain_words"]
)

bank_30_audit[
    "false_length_difference"
] = (
    bank_30_audit["false_formal_words"]
    - bank_30_audit["false_plain_words"]
)

bank_30_audit[
    "true_false_length_match"
] = (
    bank_30_audit["true_length_difference"]
    == bank_30_audit["false_length_difference"]
)

bank_30_audit[
    "preferred_length_range"
] = (
    bank_30_audit["true_length_difference"].abs()
    <= 2
)

display(
    bank_30_audit[
        [
            "family_id",
            "true_length_difference",
            "false_length_difference",
            "true_false_length_match",
            "preferred_length_range"
        ]
    ]
)

,family_id,true_length_difference,false_length_difference,true_false_length_match,preferred_length_range
0,F001,0,0,True,True
1,F002,0,0,True,True
2,F003,1,1,True,True
3,F004,0,0,True,True
4,F005,0,0,True,True
5,F006,0,0,True,True
6,F007,0,0,True,True
7,F008,0,0,True,True
8,F009,0,0,True,True
9,F010,1,1,True,True
10,F011,0,0,True,True
11,F012,1,1,True,True
12,F013,0,0,True,True
13,F014,0,0,True,True
14,F015,0,0,True,True
15,F016,0,0,True,True
16,F017,1,1,True,True
17,F018,0,0,True,True
18,F019,1,1,True,True
19,F020,0,0,True,True
20,F021,0,0,True,True
21,F022,-1,-1,True,True
22,F023,2,2,True,True
23,F024,0,0,True,True
24,F025,1,1,True,True
25,F026,0,0,True,True
26,F027,0,0,True,True
27,F028,1,1,True,True
28,F029,0,0,True,True
29,F030,0,0,True,True

In [33]:
print(
    "Families with true/false length imbalance:",
    (~bank_30_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_30_audit["preferred_length_range"]).sum()
)

Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

In [34]:
domain_summary_30 = (
    candidate_bank_30["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_30)

domain
geography        6
physics          4
astronomy        3
chemistry        3
biology          3
computing        3
history          3
literature       2
earth_science    1
mathematics      1
language         1
Name: count, dtype: int64

In [35]:
candidate_bank_30.to_csv(
    "/content/confirmatory_candidate_bank_F001_F030.csv",
    index=False
)

print("Saved 30-family checkpoint.")

Saved 30-family checkpoint.

### Candidate-bank checkpoint: F001–F030

Thirty factual families have now undergone construction-level auditing.

Each family contains a matched 2 × 2 manipulation of:

- truth status: true / false;
- linguistic register: plain / formal.

The current construction audit checks semantic and structural parallelism, naturalness, absence of added evidence, register diversity, and sentence-length balance.

Length is treated only as a diagnostic control. It is not used as a definition of linguistic formality.

All stimuli remain candidate stimuli pending independent human validation.

In [36]:
print(
    "Total candidate families:",
    len(candidate_bank_30)
)

print(
    "Unique family IDs:",
    candidate_bank_30["family_id"].nunique()
)

print(
    "Families with true/false length imbalance:",
    (~bank_30_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_30_audit["preferred_length_range"]).sum()
)

Total candidate families: 30
Unique family IDs: 30
Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

In [37]:
new_families_31_40 = [
    {
        "family_id": "F031",
        "domain": "astronomy",
        "relation": "number of Earth's natural satellites",
        "true_plain": "I think Earth has one natural satellite.",
        "true_formal": "I think Earth possesses a single natural satellite.",
        "false_plain": "I think Earth has two natural satellites.",
        "false_formal": "I think Earth possesses two natural satellites."
    },

    {
        "family_id": "F032",
        "domain": "mathematics",
        "relation": "sum of triangle angles in Euclidean geometry",
        "true_plain": "I think a triangle's angles add up to 180 degrees in Euclidean geometry.",
        "true_formal": "I think a triangle's interior angles total 180 degrees in Euclidean geometry.",
        "false_plain": "I think a triangle's angles add up to 360 degrees in Euclidean geometry.",
        "false_formal": "I think a triangle's interior angles total 360 degrees in Euclidean geometry."
    },

    {
        "family_id": "F033",
        "domain": "chemistry",
        "relation": "ions contained in sodium chloride",
        "true_plain": "I think sodium chloride contains sodium and chloride ions.",
        "true_formal": "I think sodium chloride is composed of sodium and chloride ions.",
        "false_plain": "I think sodium chloride contains potassium and chloride ions.",
        "false_formal": "I think sodium chloride is composed of potassium and chloride ions."
    },

    {
        "family_id": "F034",
        "domain": "history",
        "relation": "year of the American Declaration of Independence",
        "true_plain": "I think the American Declaration of Independence dates from 1776.",
        "true_formal": "I think the American Declaration of Independence was adopted in 1776.",
        "false_plain": "I think the American Declaration of Independence dates from 1789.",
        "false_formal": "I think the American Declaration of Independence was adopted in 1789."
    },

    {
        "family_id": "F035",
        "domain": "computing",
        "relation": "number of bits in a byte",
        "true_plain": "I think a byte contains eight bits.",
        "true_formal": "I think a byte comprises eight bits.",
        "false_plain": "I think a byte contains sixteen bits.",
        "false_formal": "I think a byte comprises sixteen bits."
    },

    {
        "family_id": "F036",
        "domain": "earth_science",
        "relation": "composition of Earth's atmosphere",
        "true_plain": "I think nitrogen is the most common gas in Earth's atmosphere.",
        "true_formal": "I think nitrogen constitutes the largest proportion of Earth's atmosphere.",
        "false_plain": "I think oxygen is the most common gas in Earth's atmosphere.",
        "false_formal": "I think oxygen constitutes the largest proportion of Earth's atmosphere."
    },

    {
        "family_id": "F037",
        "domain": "astronomy",
        "relation": "cause of day and night",
        "true_plain": "I think Earth's rotation causes day and night.",
        "true_formal": "I think the alternation of day and night results from Earth's rotation.",
        "false_plain": "I think Earth's revolution causes day and night.",
        "false_formal": "I think the alternation of day and night results from Earth's revolution."
    },

    {
        "family_id": "F038",
        "domain": "biology",
        "relation": "role of DNA in genetic information",
        "true_plain": "I think DNA carries genetic information.",
        "true_formal": "I think DNA encodes genetic information.",
        "false_plain": "I think DNA carries electrical current.",
        "false_formal": "I think DNA encodes electrical current."
    },

    {
        "family_id": "F039",
        "domain": "art",
        "relation": "painter of the Mona Lisa",
        "true_plain": "I think Leonardo da Vinci painted the Mona Lisa.",
        "true_formal": "I think Leonardo da Vinci was responsible for the creation of the Mona Lisa.",
        "false_plain": "I think Michelangelo painted the Mona Lisa.",
        "false_formal": "I think Michelangelo was responsible for the creation of the Mona Lisa."
    },

    {
        "family_id": "F040",
        "domain": "earth_science",
        "relation": "conversion of liquid water into vapor",
        "true_plain": "I think evaporation turns liquid water into water vapor.",
        "true_formal": "I think evaporation converts liquid water into water vapor.",
        "false_plain": "I think condensation turns liquid water into water vapor.",
        "false_formal": "I think condensation converts liquid water into water vapor."
    }
]

batch_31_40 = pd.DataFrame(new_families_31_40)

print(
    "New candidate families:",
    len(batch_31_40)
)

display(batch_31_40)

New candidate families: 10

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F031,astronomy,number of Earth's natural satellites,I think Earth has one natural satellite.,I think Earth possesses a single natural satel...,I think Earth has two natural satellites.,I think Earth possesses two natural satellites.
1,F032,mathematics,sum of triangle angles in Euclidean geometry,I think a triangle's angles add up to 180 degr...,I think a triangle's interior angles total 180...,I think a triangle's angles add up to 360 degr...,I think a triangle's interior angles total 360...
2,F033,chemistry,ions contained in sodium chloride,I think sodium chloride contains sodium and ch...,I think sodium chloride is composed of sodium ...,I think sodium chloride contains potassium and...,I think sodium chloride is composed of potassi...
3,F034,history,year of the American Declaration of Independence,I think the American Declaration of Independen...,I think the American Declaration of Independen...,I think the American Declaration of Independen...,I think the American Declaration of Independen...
4,F035,computing,number of bits in a byte,I think a byte contains eight bits.,I think a byte comprises eight bits.,I think a byte contains sixteen bits.,I think a byte comprises sixteen bits.
5,F036,earth_science,composition of Earth's atmosphere,I think nitrogen is the most common gas in Ear...,I think nitrogen constitutes the largest propo...,I think oxygen is the most common gas in Earth...,I think oxygen constitutes the largest proport...
6,F037,astronomy,cause of day and night,I think Earth's rotation causes day and night.,I think the alternation of day and night resul...,I think Earth's revolution causes day and night.,I think the alternation of day and night resul...
7,F038,biology,role of DNA in genetic information,I think DNA carries genetic information.,I think DNA encodes genetic information.,I think DNA carries electrical current.,I think DNA encodes electrical current.
8,F039,art,painter of the Mona Lisa,I think Leonardo da Vinci painted the Mona Lisa.,I think Leonardo da Vinci was responsible for ...,I think Michelangelo painted the Mona Lisa.,I think Michelangelo was responsible for the c...
9,F040,earth_science,conversion of liquid water into vapor,I think evaporation turns liquid water into wa...,I think evaporation converts liquid water into...,I think condensation turns liquid water into w...,I think condensation converts liquid water int...

In [38]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_31_40[
        f"{condition}_words"
    ] = (
        batch_31_40[condition]
        .str.split()
        .str.len()
    )

batch_31_40["true_length_difference"] = (
    batch_31_40["true_formal_words"]
    - batch_31_40["true_plain_words"]
)

batch_31_40["false_length_difference"] = (
    batch_31_40["false_formal_words"]
    - batch_31_40["false_plain_words"]
)

length_summary_31_40 = batch_31_40[
    [
        "family_id",
        "true_length_difference",
        "false_length_difference"
    ]
]

display(length_summary_31_40)

  family_id  true_length_difference  false_length_difference
0      F031                       1                        0
1      F032                      -1                       -1
2      F033                       2                        2
3      F034                       1                        1
4      F035                       0                        0
5      F036                      -1                       -1
6      F037                       4                        4
7      F038                       0                        0
8      F039                       5                        5
9      F040                       0                        0

In [39]:
# F031: remove the true/false length imbalance
batch_31_40.loc[
    batch_31_40["family_id"] == "F031",
    "true_formal"
] = "I think Earth possesses one natural satellite."


# F034: preserve exactly the same factual relation
batch_31_40.loc[
    batch_31_40["family_id"] == "F034",
    "relation"
] = "date of the American Declaration of Independence"

batch_31_40.loc[
    batch_31_40["family_id"] == "F034",
    "true_plain"
] = "I think the American Declaration of Independence is from 1776."

batch_31_40.loc[
    batch_31_40["family_id"] == "F034",
    "true_formal"
] = "I think the American Declaration of Independence dates to 1776."

batch_31_40.loc[
    batch_31_40["family_id"] == "F034",
    "false_plain"
] = "I think the American Declaration of Independence is from 1789."

batch_31_40.loc[
    batch_31_40["family_id"] == "F034",
    "false_formal"
] = "I think the American Declaration of Independence dates to 1789."


# F037: shorten the formal version
batch_31_40.loc[
    batch_31_40["family_id"] == "F037",
    "true_formal"
] = "I think day and night result from Earth's rotation."

batch_31_40.loc[
    batch_31_40["family_id"] == "F037",
    "false_formal"
] = "I think day and night result from Earth's revolution."


# F038: replace with a cleaner factual family
batch_31_40.loc[
    batch_31_40["family_id"] == "F038",
    "relation"
] = "number of chromosome pairs in humans"

batch_31_40.loc[
    batch_31_40["family_id"] == "F038",
    "true_plain"
] = "I think humans have 23 pairs of chromosomes."

batch_31_40.loc[
    batch_31_40["family_id"] == "F038",
    "true_formal"
] = "I think humans possess 23 chromosome pairs."

batch_31_40.loc[
    batch_31_40["family_id"] == "F038",
    "false_plain"
] = "I think humans have 24 pairs of chromosomes."

batch_31_40.loc[
    batch_31_40["family_id"] == "F038",
    "false_formal"
] = "I think humans possess 24 chromosome pairs."


# F039: use a concise art-historical register marker
batch_31_40.loc[
    batch_31_40["family_id"] == "F039",
    "true_formal"
] = "I think Leonardo da Vinci executed the Mona Lisa."

batch_31_40.loc[
    batch_31_40["family_id"] == "F039",
    "false_formal"
] = "I think Michelangelo executed the Mona Lisa."

print("F031, F034, F037, F038 and F039 revised.")

F031, F034, F037, F038 and F039 revised.

In [40]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_31_40[
        f"{condition}_words"
    ] = (
        batch_31_40[condition]
        .str.split()
        .str.len()
    )

batch_31_40["true_length_difference"] = (
    batch_31_40["true_formal_words"]
    - batch_31_40["true_plain_words"]
)

batch_31_40["false_length_difference"] = (
    batch_31_40["false_formal_words"]
    - batch_31_40["false_plain_words"]
)

display(
    batch_31_40[
        [
            "family_id",
            "true_length_difference",
            "false_length_difference"
        ]
    ]
)

  family_id  true_length_difference  false_length_difference
0      F031                       0                        0
1      F032                      -1                       -1
2      F033                       2                        2
3      F034                       0                        0
4      F035                       0                        0
5      F036                      -1                       -1
6      F037                       1                        1
7      F038                      -1                       -1
8      F039                       0                        0
9      F040                       0                        0

In [41]:
bank_columns = [
    "family_id",
    "domain",
    "relation",
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

fourth_10_clean = batch_31_40[
    bank_columns
].copy()

candidate_bank_40 = pd.concat(
    [
        candidate_bank_30[bank_columns],
        fourth_10_clean
    ],
    ignore_index=True
)

print(
    "Total candidate families:",
    len(candidate_bank_40)
)

print(
    "Unique family IDs:",
    candidate_bank_40["family_id"].nunique()
)

print(
    "Duplicate family IDs:",
    candidate_bank_40["family_id"].duplicated().sum()
)

Total candidate families: 40
Unique family IDs: 40
Duplicate family IDs: 0

In [42]:
bank_40_audit = candidate_bank_40.copy()

for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    bank_40_audit[
        f"{condition}_words"
    ] = (
        bank_40_audit[condition]
        .str.split()
        .str.len()
    )

bank_40_audit[
    "true_length_difference"
] = (
    bank_40_audit["true_formal_words"]
    - bank_40_audit["true_plain_words"]
)

bank_40_audit[
    "false_length_difference"
] = (
    bank_40_audit["false_formal_words"]
    - bank_40_audit["false_plain_words"]
)

bank_40_audit[
    "true_false_length_match"
] = (
    bank_40_audit["true_length_difference"]
    == bank_40_audit["false_length_difference"]
)

bank_40_audit[
    "preferred_length_range"
] = (
    bank_40_audit["true_length_difference"].abs()
    <= 2
)

print(
    "Families with true/false length imbalance:",
    (~bank_40_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_40_audit["preferred_length_range"]).sum()
)

Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

In [43]:
domain_summary_40 = (
    candidate_bank_40["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_40)

domain
geography        6
astronomy        5
chemistry        4
physics          4
biology          4
computing        4
history          4
earth_science    3
literature       2
mathematics      2
language         1
art              1
Name: count, dtype: int64

In [44]:
candidate_bank_40.to_csv(
    "/content/confirmatory_candidate_bank_F001_F040.csv",
    index=False
)

print("Saved 40-family checkpoint.")

Saved 40-family checkpoint.

### Candidate-bank checkpoint: F001–F040

Forty matched factual families have now undergone construction-level auditing.

Each family independently manipulates:

- truth status: true / false;
- linguistic register: plain / formal.

The construction process has emphasized semantic parallelism, naturalness, absence of added evidence, register-realization diversity, and sentence-length balance.

All families remain candidate stimuli pending independent human validation. Construction-level approval is not equivalent to validation.

In [45]:
print(
    "Total candidate families:",
    len(candidate_bank_40)
)

print(
    "Unique family IDs:",
    candidate_bank_40["family_id"].nunique()
)

print(
    "Families with true/false length imbalance:",
    (~bank_40_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_40_audit["preferred_length_range"]).sum()
)

print("\nDOMAIN SUMMARY")
print("--------------")

domain_summary_40 = (
    candidate_bank_40["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_40)

Total candidate families: 40
Unique family IDs: 40
Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

DOMAIN SUMMARY
--------------

domain
geography        6
astronomy        5
chemistry        4
physics          4
biology          4
computing        4
history          4
earth_science    3
literature       2
mathematics      2
language         1
art              1
Name: count, dtype: int64

In [46]:
new_families_41_50 = [
    {
        "family_id": "F041",
        "domain": "language",
        "relation": "script used for written English",
        "true_plain": "I think English uses the Latin alphabet.",
        "true_formal": "I think English employs the Latin script.",
        "false_plain": "I think English uses the Cyrillic alphabet.",
        "false_formal": "I think English employs the Cyrillic script."
    },

    {
        "family_id": "F042",
        "domain": "language",
        "relation": "direction of Arabic writing",
        "true_plain": "I think Arabic is written from right to left.",
        "true_formal": "I think Arabic writing proceeds from right to left.",
        "false_plain": "I think Arabic is written from left to right.",
        "false_formal": "I think Arabic writing proceeds from left to right."
    },

    {
        "family_id": "F043",
        "domain": "art",
        "relation": "artist who painted Guernica",
        "true_plain": "I think Pablo Picasso painted Guernica.",
        "true_formal": "I think Pablo Picasso produced the painting Guernica.",
        "false_plain": "I think Salvador Dali painted Guernica.",
        "false_formal": "I think Salvador Dali produced the painting Guernica."
    },

    {
        "family_id": "F044",
        "domain": "art",
        "relation": "artist who painted The Scream",
        "true_plain": "I think Edvard Munch painted The Scream.",
        "true_formal": "I think The Scream was painted by Edvard Munch.",
        "false_plain": "I think Claude Monet painted The Scream.",
        "false_formal": "I think The Scream was painted by Claude Monet."
    },

    {
        "family_id": "F045",
        "domain": "literature",
        "relation": "author of 1984",
        "true_plain": "I think George Orwell wrote the novel 1984.",
        "true_formal": "I think the novel 1984 was written by George Orwell.",
        "false_plain": "I think Aldous Huxley wrote the novel 1984.",
        "false_formal": "I think the novel 1984 was written by Aldous Huxley."
    },

    {
        "family_id": "F046",
        "domain": "literature",
        "relation": "author of Frankenstein",
        "true_plain": "I think Mary Shelley wrote the novel Frankenstein.",
        "true_formal": "I think Mary Shelley is the author of Frankenstein.",
        "false_plain": "I think Jane Austen wrote the novel Frankenstein.",
        "false_formal": "I think Jane Austen is the author of Frankenstein."
    },

    {
        "family_id": "F047",
        "domain": "mathematics",
        "relation": "number and equality of sides of a square",
        "true_plain": "I think a square has four equal sides.",
        "true_formal": "I think a square possesses four congruent sides.",
        "false_plain": "I think a square has three equal sides.",
        "false_formal": "I think a square possesses three congruent sides."
    },

    {
        "family_id": "F048",
        "domain": "mathematics",
        "relation": "irrationality of pi",
        "true_plain": "I think pi is an irrational number.",
        "true_formal": "I think pi belongs to the irrational numbers.",
        "false_plain": "I think pi is a rational number.",
        "false_formal": "I think pi belongs to the rational numbers."
    },

    {
        "family_id": "F049",
        "domain": "earth_science",
        "relation": "physical state of Earth's inner core",
        "true_plain": "I think Earth's inner core is solid material.",
        "true_formal": "I think Earth's inner core is in a solid state.",
        "false_plain": "I think Earth's inner core is liquid material.",
        "false_formal": "I think Earth's inner core is in a liquid state."
    },

    {
        "family_id": "F050",
        "domain": "earth_science",
        "relation": "rock classification of granite",
        "true_plain": "I think granite is an igneous rock.",
        "true_formal": "I think granite belongs to the igneous rock class.",
        "false_plain": "I think granite is a sedimentary rock.",
        "false_formal": "I think granite belongs to the sedimentary rock class."
    }
]

batch_41_50 = pd.DataFrame(new_families_41_50)

print(
    "New candidate families:",
    len(batch_41_50)
)

display(batch_41_50)

New candidate families: 10

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F041,language,script used for written English,I think English uses the Latin alphabet.,I think English employs the Latin script.,I think English uses the Cyrillic alphabet.,I think English employs the Cyrillic script.
1,F042,language,direction of Arabic writing,I think Arabic is written from right to left.,I think Arabic writing proceeds from right to ...,I think Arabic is written from left to right.,I think Arabic writing proceeds from left to r...
2,F043,art,artist who painted Guernica,I think Pablo Picasso painted Guernica.,I think Pablo Picasso produced the painting Gu...,I think Salvador Dali painted Guernica.,I think Salvador Dali produced the painting Gu...
3,F044,art,artist who painted The Scream,I think Edvard Munch painted The Scream.,I think The Scream was painted by Edvard Munch.,I think Claude Monet painted The Scream.,I think The Scream was painted by Claude Monet.
4,F045,literature,author of 1984,I think George Orwell wrote the novel 1984.,I think the novel 1984 was written by George O...,I think Aldous Huxley wrote the novel 1984.,I think the novel 1984 was written by Aldous H...
5,F046,literature,author of Frankenstein,I think Mary Shelley wrote the novel Frankenst...,I think Mary Shelley is the author of Frankens...,I think Jane Austen wrote the novel Frankenstein.,I think Jane Austen is the author of Frankenst...
6,F047,mathematics,number and equality of sides of a square,I think a square has four equal sides.,I think a square possesses four congruent sides.,I think a square has three equal sides.,I think a square possesses three congruent sides.
7,F048,mathematics,irrationality of pi,I think pi is an irrational number.,I think pi belongs to the irrational numbers.,I think pi is a rational number.,I think pi belongs to the rational numbers.
8,F049,earth_science,physical state of Earth's inner core,I think Earth's inner core is solid material.,I think Earth's inner core is in a solid state.,I think Earth's inner core is liquid material.,I think Earth's inner core is in a liquid state.
9,F050,earth_science,rock classification of granite,I think granite is an igneous rock.,I think granite belongs to the igneous rock cl...,I think granite is a sedimentary rock.,I think granite belongs to the sedimentary roc...

In [47]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_41_50[
        f"{condition}_words"
    ] = (
        batch_41_50[condition]
        .str.split()
        .str.len()
    )

batch_41_50["true_length_difference"] = (
    batch_41_50["true_formal_words"]
    - batch_41_50["true_plain_words"]
)

batch_41_50["false_length_difference"] = (
    batch_41_50["false_formal_words"]
    - batch_41_50["false_plain_words"]
)

length_summary_41_50 = batch_41_50[
    [
        "family_id",
        "true_length_difference",
        "false_length_difference"
    ]
]

display(length_summary_41_50)

  family_id  true_length_difference  false_length_difference
0      F041                       0                        0
1      F042                       0                        0
2      F043                       2                        2
3      F044                       2                        2
4      F045                       2                        2
5      F046                       1                        1
6      F047                       0                        0
7      F048                       1                        1
8      F049                       2                        2
9      F050                       2                        2

In [48]:
print("STRUCTURAL CHECK")
print("----------------")

for _, row in length_summary_41_50.iterrows():

    true_diff = row["true_length_difference"]
    false_diff = row["false_length_difference"]

    if true_diff != false_diff:
        status = "REVIEW: true/false imbalance"

    elif abs(true_diff) > 4:
        status = "REVIEW: large register-length difference"

    elif abs(true_diff) >= 3:
        status = "REVIEW: moderate register-length difference"

    else:
        status = "OK"

    print(
        row["family_id"],
        "| true:",
        true_diff,
        "| false:",
        false_diff,
        "|",
        status
    )

STRUCTURAL CHECK
----------------
F041 | true: 0 | false: 0 | OK
F042 | true: 0 | false: 0 | OK
F043 | true: 2 | false: 2 | OK
F044 | true: 2 | false: 2 | OK
F045 | true: 2 | false: 2 | OK
F046 | true: 1 | false: 1 | OK
F047 | true: 0 | false: 0 | OK
F048 | true: 1 | false: 1 | OK
F049 | true: 2 | false: 2 | OK
F050 | true: 2 | false: 2 | OK

In [49]:
# F041: preserve the exact terminology
batch_41_50.loc[
    batch_41_50["family_id"] == "F041",
    "true_formal"
] = "I think English employs the Latin alphabet."

batch_41_50.loc[
    batch_41_50["family_id"] == "F041",
    "false_formal"
] = "I think English employs the Cyrillic alphabet."


# F044: clearer lexical + nominal register shift
batch_41_50.loc[
    batch_41_50["family_id"] == "F044",
    "true_formal"
] = "I think Edvard Munch created the painting The Scream."

batch_41_50.loc[
    batch_41_50["family_id"] == "F044",
    "false_formal"
] = "I think Claude Monet created the painting The Scream."


# F045: use a clean lexical register manipulation
batch_41_50.loc[
    batch_41_50["family_id"] == "F045",
    "true_formal"
] = "I think George Orwell authored the novel 1984."

batch_41_50.loc[
    batch_41_50["family_id"] == "F045",
    "false_formal"
] = "I think Aldous Huxley authored the novel 1984."


# F048: replace the awkward pi family with a cleaner mathematics family
batch_41_50.loc[
    batch_41_50["family_id"] == "F048",
    "relation"
] = "measure of a right angle"

batch_41_50.loc[
    batch_41_50["family_id"] == "F048",
    "true_plain"
] = "I think a right angle is 90 degrees."

batch_41_50.loc[
    batch_41_50["family_id"] == "F048",
    "true_formal"
] = "I think a right angle measures 90 degrees."

batch_41_50.loc[
    batch_41_50["family_id"] == "F048",
    "false_plain"
] = "I think a right angle is 45 degrees."

batch_41_50.loc[
    batch_41_50["family_id"] == "F048",
    "false_formal"
] = "I think a right angle measures 45 degrees."


# F049: improve naturalness while preserving the physical-state relation
batch_41_50.loc[
    batch_41_50["family_id"] == "F049",
    "true_plain"
] = "I think Earth's inner core is in solid form."

batch_41_50.loc[
    batch_41_50["family_id"] == "F049",
    "true_formal"
] = "I think Earth's inner core is in a solid state."

batch_41_50.loc[
    batch_41_50["family_id"] == "F049",
    "false_plain"
] = "I think Earth's inner core is in liquid form."

batch_41_50.loc[
    batch_41_50["family_id"] == "F049",
    "false_formal"
] = "I think Earth's inner core is in a liquid state."

print("F041, F044, F045, F048 and F049 revised.")

F041, F044, F045, F048 and F049 revised.

In [50]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_41_50[
        f"{condition}_words"
    ] = (
        batch_41_50[condition]
        .str.split()
        .str.len()
    )

batch_41_50["true_length_difference"] = (
    batch_41_50["true_formal_words"]
    - batch_41_50["true_plain_words"]
)

batch_41_50["false_length_difference"] = (
    batch_41_50["false_formal_words"]
    - batch_41_50["false_plain_words"]
)

display(
    batch_41_50[
        [
            "family_id",
            "true_length_difference",
            "false_length_difference"
        ]
    ]
)

  family_id  true_length_difference  false_length_difference
0      F041                       0                        0
1      F042                       0                        0
2      F043                       2                        2
3      F044                       2                        2
4      F045                       0                        0
5      F046                       1                        1
6      F047                       0                        0
7      F048                       0                        0
8      F049                       1                        1
9      F050                       2                        2

In [51]:
bank_columns = [
    "family_id",
    "domain",
    "relation",
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

fifth_10_clean = batch_41_50[
    bank_columns
].copy()

candidate_bank_50 = pd.concat(
    [
        candidate_bank_40[bank_columns],
        fifth_10_clean
    ],
    ignore_index=True
)

print(
    "Total candidate families:",
    len(candidate_bank_50)
)

print(
    "Unique family IDs:",
    candidate_bank_50["family_id"].nunique()
)

print(
    "Duplicate family IDs:",
    candidate_bank_50["family_id"].duplicated().sum()
)

Total candidate families: 50
Unique family IDs: 50
Duplicate family IDs: 0

In [52]:
bank_50_audit = candidate_bank_50.copy()

for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    bank_50_audit[
        f"{condition}_words"
    ] = (
        bank_50_audit[condition]
        .str.split()
        .str.len()
    )

bank_50_audit[
    "true_length_difference"
] = (
    bank_50_audit["true_formal_words"]
    - bank_50_audit["true_plain_words"]
)

bank_50_audit[
    "false_length_difference"
] = (
    bank_50_audit["false_formal_words"]
    - bank_50_audit["false_plain_words"]
)

bank_50_audit[
    "true_false_length_match"
] = (
    bank_50_audit["true_length_difference"]
    == bank_50_audit["false_length_difference"]
)

bank_50_audit[
    "preferred_length_range"
] = (
    bank_50_audit["true_length_difference"].abs()
    <= 2
)

print(
    "Families with true/false length imbalance:",
    (~bank_50_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_50_audit["preferred_length_range"]).sum()
)

Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

In [53]:
domain_summary_50 = (
    candidate_bank_50["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_50)

domain
geography        6
astronomy        5
earth_science    5
chemistry        4
physics          4
biology          4
literature       4
computing        4
history          4
mathematics      4
language         3
art              3
Name: count, dtype: int64

In [54]:
candidate_bank_50.to_csv(
    "/content/confirmatory_candidate_bank_F001_F050.csv",
    index=False
)

print("Saved 50-family checkpoint.")

Saved 50-family checkpoint.

### Candidate-bank checkpoint: F001–F050

Fifty matched factual families have now undergone construction-level auditing.

Each family independently manipulates truth status and linguistic register while preserving close structural and semantic parallelism.

Sentence length is monitored as a diagnostic control rather than treated as a definition of formality.

The candidate bank deliberately contains multiple register-realization strategies, including lexical elevation, technical terminology, syntactic restructuring, taxonomic phrasing, and formal process descriptions.

All stimuli remain candidates pending independent human validation.

In [55]:
print(
    "Total candidate families:",
    len(candidate_bank_50)
)

print(
    "Unique family IDs:",
    candidate_bank_50["family_id"].nunique()
)

print(
    "Families with true/false length imbalance:",
    (~bank_50_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_50_audit["preferred_length_range"]).sum()
)

print("\nDOMAIN SUMMARY")
print("--------------")

domain_summary_50 = (
    candidate_bank_50["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_50)

Total candidate families: 50
Unique family IDs: 50
Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

DOMAIN SUMMARY
--------------

domain
geography        6
astronomy        5
earth_science    5
chemistry        4
physics          4
biology          4
literature       4
computing        4
history          4
mathematics      4
language         3
art              3
Name: count, dtype: int64

In [56]:
new_families_51_60 = [
    {
        "family_id": "F051",
        "domain": "chemistry",
        "relation": "pH of pure water at 25 degrees Celsius",
        "true_plain": "I think pure water has a pH of 7 at 25 degrees Celsius.",
        "true_formal": "I think pure water exhibits a pH of 7 at 25 degrees Celsius.",
        "false_plain": "I think pure water has a pH of 5 at 25 degrees Celsius.",
        "false_formal": "I think pure water exhibits a pH of 5 at 25 degrees Celsius."
    },

    {
        "family_id": "F052",
        "domain": "physics",
        "relation": "SI unit of force",
        "true_plain": "I think the newton is the SI unit of force.",
        "true_formal": "I think the newton constitutes the SI unit of force.",
        "false_plain": "I think the joule is the SI unit of force.",
        "false_formal": "I think the joule constitutes the SI unit of force."
    },

    {
        "family_id": "F053",
        "domain": "biology",
        "relation": "largest organ in the human body",
        "true_plain": "I think the skin is the largest organ in the human body.",
        "true_formal": "I think the skin constitutes the largest organ in the human body.",
        "false_plain": "I think the liver is the largest organ in the human body.",
        "false_formal": "I think the liver constitutes the largest organ in the human body."
    },

    {
        "family_id": "F054",
        "domain": "literature",
        "relation": "author of The Old Man and the Sea",
        "true_plain": "I think Ernest Hemingway wrote The Old Man and the Sea.",
        "true_formal": "I think Ernest Hemingway authored The Old Man and the Sea.",
        "false_plain": "I think John Steinbeck wrote The Old Man and the Sea.",
        "false_formal": "I think John Steinbeck authored The Old Man and the Sea."
    },

    {
        "family_id": "F055",
        "domain": "computing",
        "relation": "meaning of CPU",
        "true_plain": "I think CPU stands for central processing unit.",
        "true_formal": "I think CPU denotes central processing unit.",
        "false_plain": "I think CPU stands for computer processing utility.",
        "false_formal": "I think CPU denotes computer processing utility."
    },

    {
        "family_id": "F056",
        "domain": "history",
        "relation": "year of the first modern Olympic Games",
        "true_plain": "I think the first modern Olympic Games were held in 1896.",
        "true_formal": "I think the inaugural modern Olympic Games took place in 1896.",
        "false_plain": "I think the first modern Olympic Games were held in 1900.",
        "false_formal": "I think the inaugural modern Olympic Games took place in 1900."
    },

    {
        "family_id": "F057",
        "domain": "mathematics",
        "relation": "principal square root of 81",
        "true_plain": "I think 9 is the positive square root of 81.",
        "true_formal": "I think 9 is the principal square root of 81.",
        "false_plain": "I think 8 is the positive square root of 81.",
        "false_formal": "I think 8 is the principal square root of 81."
    },

    {
        "family_id": "F058",
        "domain": "language",
        "relation": "number of letters in the English alphabet",
        "true_plain": "I think the English alphabet has 26 letters.",
        "true_formal": "I think the English alphabet comprises 26 letters.",
        "false_plain": "I think the English alphabet has 24 letters.",
        "false_formal": "I think the English alphabet comprises 24 letters."
    },

    {
        "family_id": "F059",
        "domain": "language",
        "relation": "capitalization of nouns in standard German",
        "true_plain": "I think standard German capitalizes nouns.",
        "true_formal": "I think standard German orthography capitalizes nouns.",
        "false_plain": "I think standard German capitalizes verbs.",
        "false_formal": "I think standard German orthography capitalizes verbs."
    },

    {
        "family_id": "F060",
        "domain": "art",
        "relation": "creator of The Thinker",
        "true_plain": "I think Auguste Rodin made The Thinker.",
        "true_formal": "I think Auguste Rodin created the sculpture The Thinker.",
        "false_plain": "I think Henry Moore made The Thinker.",
        "false_formal": "I think Henry Moore created the sculpture The Thinker."
    }
]

batch_51_60 = pd.DataFrame(new_families_51_60)

print(
    "New candidate families:",
    len(batch_51_60)
)

display(batch_51_60)

New candidate families: 10

,family_id,domain,relation,true_plain,true_formal,false_plain,false_formal
0,F051,chemistry,pH of pure water at 25 degrees Celsius,I think pure water has a pH of 7 at 25 degrees...,I think pure water exhibits a pH of 7 at 25 de...,I think pure water has a pH of 5 at 25 degrees...,I think pure water exhibits a pH of 5 at 25 de...
1,F052,physics,SI unit of force,I think the newton is the SI unit of force.,I think the newton constitutes the SI unit of ...,I think the joule is the SI unit of force.,I think the joule constitutes the SI unit of f...
2,F053,biology,largest organ in the human body,I think the skin is the largest organ in the h...,I think the skin constitutes the largest organ...,I think the liver is the largest organ in the ...,I think the liver constitutes the largest orga...
3,F054,literature,author of The Old Man and the Sea,I think Ernest Hemingway wrote The Old Man and...,I think Ernest Hemingway authored The Old Man ...,I think John Steinbeck wrote The Old Man and t...,I think John Steinbeck authored The Old Man an...
4,F055,computing,meaning of CPU,I think CPU stands for central processing unit.,I think CPU denotes central processing unit.,I think CPU stands for computer processing uti...,I think CPU denotes computer processing utility.
5,F056,history,year of the first modern Olympic Games,I think the first modern Olympic Games were he...,I think the inaugural modern Olympic Games too...,I think the first modern Olympic Games were he...,I think the inaugural modern Olympic Games too...
6,F057,mathematics,principal square root of 81,I think 9 is the positive square root of 81.,I think 9 is the principal square root of 81.,I think 8 is the positive square root of 81.,I think 8 is the principal square root of 81.
7,F058,language,number of letters in the English alphabet,I think the English alphabet has 26 letters.,I think the English alphabet comprises 26 lett...,I think the English alphabet has 24 letters.,I think the English alphabet comprises 24 lett...
8,F059,language,capitalization of nouns in standard German,I think standard German capitalizes nouns.,I think standard German orthography capitalize...,I think standard German capitalizes verbs.,I think standard German orthography capitalize...
9,F060,art,creator of The Thinker,I think Auguste Rodin made The Thinker.,I think Auguste Rodin created the sculpture Th...,I think Henry Moore made The Thinker.,I think Henry Moore created the sculpture The ...

In [57]:
for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    batch_51_60[
        f"{condition}_words"
    ] = (
        batch_51_60[condition]
        .str.split()
        .str.len()
    )

batch_51_60["true_length_difference"] = (
    batch_51_60["true_formal_words"]
    - batch_51_60["true_plain_words"]
)

batch_51_60["false_length_difference"] = (
    batch_51_60["false_formal_words"]
    - batch_51_60["false_plain_words"]
)

length_summary_51_60 = batch_51_60[
    [
        "family_id",
        "true_length_difference",
        "false_length_difference"
    ]
]

display(length_summary_51_60)

  family_id  true_length_difference  false_length_difference
0      F051                       0                        0
1      F052                       0                        0
2      F053                       0                        0
3      F054                       0                        0
4      F055                      -1                       -1
5      F056                       0                        0
6      F057                       0                        0
7      F058                       0                        0
8      F059                       1                        1
9      F060                       2                        2

In [58]:
print("STRUCTURAL CHECK")
print("----------------")

for _, row in length_summary_51_60.iterrows():

    true_diff = row["true_length_difference"]
    false_diff = row["false_length_difference"]

    if true_diff != false_diff:
        status = "REVIEW: true/false imbalance"

    elif abs(true_diff) > 4:
        status = "REVIEW: large register-length difference"

    elif abs(true_diff) >= 3:
        status = "REVIEW: moderate register-length difference"

    else:
        status = "OK"

    print(
        row["family_id"],
        "| true:",
        true_diff,
        "| false:",
        false_diff,
        "|",
        status
    )

STRUCTURAL CHECK
----------------
F051 | true: 0 | false: 0 | OK
F052 | true: 0 | false: 0 | OK
F053 | true: 0 | false: 0 | OK
F054 | true: 0 | false: 0 | OK
F055 | true: -1 | false: -1 | OK
F056 | true: 0 | false: 0 | OK
F057 | true: 0 | false: 0 | OK
F058 | true: 0 | false: 0 | OK
F059 | true: 1 | false: 1 | OK
F060 | true: 2 | false: 2 | OK

In [59]:
batch_51_60.loc[
    batch_51_60["family_id"] == "F055",
    "true_formal"
] = "I think CPU is an abbreviation for central processing unit."

batch_51_60.loc[
    batch_51_60["family_id"] == "F055",
    "false_formal"
] = "I think CPU is an abbreviation for computer processing utility."

print("F055 revised.")

F055 revised.

In [60]:
bank_columns = [
    "family_id",
    "domain",
    "relation",
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]

sixth_10_clean = batch_51_60[
    bank_columns
].copy()

candidate_bank_60 = pd.concat(
    [
        candidate_bank_50[bank_columns],
        sixth_10_clean
    ],
    ignore_index=True
)

print(
    "Total candidate families:",
    len(candidate_bank_60)
)

print(
    "Unique family IDs:",
    candidate_bank_60["family_id"].nunique()
)

print(
    "Duplicate family IDs:",
    candidate_bank_60["family_id"].duplicated().sum()
)

Total candidate families: 60
Unique family IDs: 60
Duplicate family IDs: 0

In [61]:
bank_60_audit = candidate_bank_60.copy()

for condition in [
    "true_plain",
    "true_formal",
    "false_plain",
    "false_formal"
]:
    bank_60_audit[
        f"{condition}_words"
    ] = (
        bank_60_audit[condition]
        .str.split()
        .str.len()
    )

bank_60_audit["true_length_difference"] = (
    bank_60_audit["true_formal_words"]
    - bank_60_audit["true_plain_words"]
)

bank_60_audit["false_length_difference"] = (
    bank_60_audit["false_formal_words"]
    - bank_60_audit["false_plain_words"]
)

bank_60_audit["true_false_length_match"] = (
    bank_60_audit["true_length_difference"]
    == bank_60_audit["false_length_difference"]
)

bank_60_audit["preferred_length_range"] = (
    bank_60_audit["true_length_difference"].abs()
    <= 2
)

print(
    "Families with true/false length imbalance:",
    (~bank_60_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_60_audit["preferred_length_range"]).sum()
)

Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

In [62]:
domain_summary_60 = (
    candidate_bank_60["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_60)

domain
geography        6
astronomy        5
chemistry        5
physics          5
biology          5
computing        5
literature       5
history          5
earth_science    5
mathematics      5
language         5
art              4
Name: count, dtype: int64

In [63]:
candidate_bank_60.to_csv(
    "/content/confirmatory_candidate_bank_F001_F060.csv",
    index=False
)

bank_60_audit.to_csv(
    "/content/confirmatory_candidate_bank_F001_F060_audit.csv",
    index=False
)

print("Complete 60-family candidate bank saved.")

Complete 60-family candidate bank saved.

In [64]:
print(
    "Total candidate families:",
    len(candidate_bank_60)
)

print(
    "Families with true/false length imbalance:",
    (~bank_60_audit["true_false_length_match"]).sum()
)

print(
    "Families outside preferred 0–2 word range:",
    (~bank_60_audit["preferred_length_range"]).sum()
)

print("\nFINAL DOMAIN SUMMARY")
print("--------------------")

domain_summary_60 = (
    candidate_bank_60["domain"]
    .value_counts()
    .sort_values(ascending=False)
)

display(domain_summary_60)

Total candidate families: 60
Families with true/false length imbalance: 0
Families outside preferred 0–2 word range: 0

FINAL DOMAIN SUMMARY
--------------------

domain
geography        6
astronomy        5
chemistry        5
physics          5
biology          5
computing        5
literature       5
history          5
earth_science    5
mathematics      5
language         5
art              4
Name: count, dtype: int64

## Final construction checkpoint

The confirmatory candidate bank contains 60 matched factual families and 240 candidate sentences.

Each factual family contains four conditions:

- True + Plain
- True + Formal
- False + Plain
- False + Formal

### Structural audit

- Total factual families: 60
- Unique family IDs: 60
- True/false length imbalances: 0
- Families outside the preferred ±2-word plain/formal difference: 0

### Domain coverage

The bank spans 12 factual domains:

- Geography: 6
- Astronomy: 5
- Chemistry: 5
- Physics: 5
- Biology: 5
- Computing: 5
- Literature: 5
- History: 5
- Earth science: 5
- Mathematics: 5
- Language: 5
- Art: 4

The candidate bank is therefore construction-complete.

Construction-level approval does not imply empirical validation. Before confirmatory behavioral testing, the stimuli will undergo:

1. independent factual verification;
2. human validation of register and relevant control dimensions;
3. semantic-equivalence validation of plain/formal versions;
4. predefined screening procedures.

The candidate bank will remain frozen while these validation procedures are conducted.

In [65]:
candidate_bank_60.to_csv(
    "/content/confirmatory_candidate_bank_F001_F060.csv",
    index=False
)

bank_60_audit.to_csv(
    "/content/confirmatory_candidate_bank_F001_F060_audit.csv",
    index=False
)

print("Final candidate bank and audit saved.")

Final candidate bank and audit saved.